### ISSUE TITLE
Rename the repo to THOR

### ISSUE THREAD

**Issue by elemoine** [GFDRR/thinkhazard#1]
Should we rename the repo from "thinkhazard" to "thor"?

We plan to start adding content to the repo this week, so we'd like the sort out the question of the repo name first :-)

Thanks.

**Comment by ingenieroariel** [comment]
Works for me.

+1

**Comment by vdeparday** [comment]
Since the website will be thinkhazard.org , I am in favor of keeping thinkhazard because I feel like it is more likely to get googled, what do you think??It is also more self-explanatory if people are browsing our repos. But either way is fine, it is just the repo name

**Comment by elemoine** [comment]
It is really up to you. I just thought you'd like one single name, and that that name was thor.

**Comment by ingenieroariel** [comment]
I am happy to keep the repo name as thinkhazard too, on our end it is up to
just Vivien and myself. Let's also agree to not change mid project (it will
be GFDRR/thinkhazard at least until June 2016).

Sounds good?

**Comment by elemoine** [comment]
Ok. Closing.

**Comment by vdeparday** [comment]
Sounds good, one is more the tag line and one is the abbreviation of the full name. I think either can work, it is just nice to have something self-explanatory rather than acronym for the repo like for the domain name.
