### ISSUE TITLE
Highlight area perimeter on mouse over

### ISSUE THREAD

**Issue by ingenieroariel** [GFDRR/thinkhazard#104]
To incite the user to click on it and discover the behavior.

**Comment by elemoine** [comment]
To incite the user to click on a sub-division we currently change the mouse cursor. To make it even more explicit/visible to the user we could also display a popup/tooltip.

But highlighting the area perimeter is a problem technically. We use UTFGrid for performance reasons, and the UTFGrid does not contain the polygon coordinates. We could use Ajax requests to get the coordinates, but that would be slow, defeating the purpose of using UTFGrid.

**Comment by ingenieroariel** [comment]
Thanks for the explanation. We can look into this after the alpha then, a
simplified-polygons pre-cached version of them may not be slow.

In the meantime, I really liked the "Zoom out to Morocco" button, the idea
to put the name on the outer area was great. Similarly, we could do here
"Zoom in to Blah Blah" as a pop up on mouse over.

-a

**Comment by fvanderbiest** [comment]
> we could do here "Zoom in to Blah Blah" as a pop up on mouse over.

+1

**Comment by pgiraud** [comment]
We discussed the "highlight" a bit more here at camptocamp.
As already explained by Éric, highlight on hover requires vector data (coordinates) client side. This means requesting the server to get the vector representation of the data (probably as GeoJSON) instead of asking for an image (along with UTFGrid) as we currently do.
Then, we wouldn't need to rely on Mapnik any more and the rendering of the administrative divisions would be done in the browser.

Is the highlight a "must-have" or a "nice-to-have"?

**Comment by ingenieroariel** [comment]
The highlight is a nice-to-have but a better way to show feedback to the
user on what they are about to do is a must-have.

It is common to use CSS to change color of the item you are about to click
to let users knows they can click on it. Here is an example of the strategy
in action for a bar chart:

Here is the example that I showed the team in Orleans that showcases the
sort of usability we would expect from the tool:

http://www.tnoda.com/blog/2013-12-07

It lets you zoom into countries and small admin divisions (only USA and
Japan) and does it very smoothly without overloading the browser.

**Comment by nchauvin-brgm** [comment]
Hover feature is not compatible with touch-based devices (Éric reminded me of that some time ago), but it can provide a better experience in navigation on mouse-based devices, as Ariel points out.
If we mean to make THOR compatible with touch-based devices, it therefore can't be a "must-have", but rather an "extra" or "nice-to-have" for mouse-based devices.
