### ISSUE TITLE
Encoding issues for map labels

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#112]
Spotted with "La Réunion" island
![capture du 2015-05-19 04 42 17](https://cloud.githubusercontent.com/assets/265319/7698864/a14ff1de-fde1-11e4-9fdb-34c4a33a03a9.png)

To my knowledge, accentuated chars where mostly absent from the original dataset.

**Comment by fvanderbiest** [comment]
@ingenieroariel would like that accentuated chars be replaced by their unaccentuated equivalents during datamart population

**Comment by flyonnais-brgm** [comment]
The accentuated characters are well encoded in the GFDRR source file as well as in the datamart (utf-8).
Could you check from the client side ?

**Comment by pgiraud** [comment]
We probably forgot to configure something in the mapnik layer. We'll check that. Thanks.
