### ISSUE TITLE
search field: "enter" should bring user to location

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#113]
For the 1.0 version : choose the location whose name matches "at best" the provided one.

For the alpha version : choose the first one, and if there's no result, display "no result"

**Comment by ingenieroariel** [comment]
:+1:

**Comment by elemoine** [comment]
> This is particularly important for people with slow connections that do not get the suggestions.

Loading the report page requires an admin level identifier, so a response from the search service. So we can't load the report page before we get suggestions from the search service.

What we can probably do though is select the first suggestion when the user just presses enter after the suggestions are displayed.

**Comment by ingenieroariel** [comment]
It could be done by triggering a full page refresh after enter.

What would change is the ability to show 'no results' if nothing matches.

People are used to search engines and address bars. I believe the behavior
we should mimic is the one those have.
