### ISSUE TITLE
Additional info : the last one is not clickable

### ISSUE THREAD

**Issue by fjacon** [GFDRR/thinkhazard#114]
http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/thinkhazard/wsgi/report?divisioncode=169#EQ

**Comment by pgiraud** [comment]
When I first looked at this issue, I figured out that it was due to the fact that the report couldn't be scrolled down enough. Thus the second link was partially hidden behind a mask.
However, I can't reproduce anymore.
@fjacon can you confirm that this is OK now?

**Comment by fvanderbiest** [comment]
I can reproduce on FF38, not on chromium.

**Comment by fjacon** [comment]
still the case here :

http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/thinkhazard/wsgi/report?divisioncode=169#EQ

on FF

2015-05-21 17:10 GMT+02:00 Pierre GIRAUD <notifications@github.com>:

> When I first looked at this issue, I figured out that it was due to the
> fact that the report couldn't be scrolled down enough. Thus the second link
> was partially hidden behind a mask.
> However, I can't reproduce anymore.
> @fjacon <https://github.com/fjacon> can you confirm that this is OK now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GFDRR/thinkhazard/issues/114#issuecomment-104313881>.
>



-- 
Frédéric Jacon
Responsable d'agence - Chef de projets
Camptocamp France
Savoie Technolac
BP 352
48 avenue du Lac du Bourget
73372 Le Bourget du Lac, Cedex
www.camptocamp.com

+33 614 71 28 24 (mobile)
+33 458 48 20 38 (direct France)
+33 458 48 20 00 (standard)
+33 458 48 20 10 (fax)

**Comment by elemoine** [comment]
Yes, this occurs when the screen is small enough and a scrollbar is used in the content panel.
