### ISSUE TITLE
Clean urls

### ISSUE THREAD

**Issue by ingenieroariel** [GFDRR/thinkhazard#116]
We should have clean urls, like the following:

http://thinkhazard.org/morocco/

http://thinkhazard.org/morocco/#earthquake

http://thinkhazard.org/morocco/ben-slimane/#flood

**Comment by pgiraud** [comment]
Won't fix for beta1. Chaning milestone.

**Comment by pgiraud** [comment]
URL could look like http://thinkhazard.org/169-morocco-ben-slimane/flood
And the route would look like {id:\d+}-{slug}/{hazard_type}.

We should then be able to generate a sitemap with all the links to countries. Hidden links to subdivisions may need to be added.

**Comment by pgiraud** [comment]
Fixed with #516.
