### ISSUE TITLE
Addition information links: new window

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#117]
It would be useful for additional information links to open in a new window, rather than closing THOR. Users are likely to want to open several additional info links.

**Comment by fvanderbiest** [comment]
This is a very controversial question ...

References:
 * against: http://www.smashingmagazine.com/2008/07/01/should-links-open-in-new-windows/
 * pro: http://uxmovement.com/navigation/why-external-links-should-open-in-new-tabs/
 * another discussion: http://www.reddit.com/r/web_design/comments/1i5hfh/should_you_use_target_blank_for_external_links/

**Comment by stufraser1** [comment]
I absolutely take these points on board, and they are interesting to read. In this case, I believe we require the utility to have the user click multiple links without incurring 'back button fatigue'. But you are the developers so happy to take your advice and ultimate decision!

**Comment by ingenieroariel** [comment]
Since we expect them to open more than one of the links I am with @stufraser1 that the right thing should be to open in a new tab.

**Comment by nchauvin-brgm** [comment]
As for me, I always advise against opening links in new window or tab, as it has to be the choice of the users. If they want to do so, they can press Ctrl and click on the link, or right-click on it and then select "open link in new tab". And if they forgot to do that, they can use the back button, which they do quite easily.
