### ISSUE TITLE
restrict access to demo server 

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#119]
Search engines already crawled our demo server, see eg https://www.google.com/webhp?q=camptocamp+think+hazard#safe=off&q=camptocamp+think+hazard

Starting tomorrow (after the testings), we might need to restrict access to the public UI

**Comment by elemoine** [comment]
I've just added a robots.txt file that blocks access to search engines.

**Comment by elemoine** [comment]
@ingenieroariel, I added a robots.txt file to prevent crawling. Do we also need to restrict access with login/password? Thanks.
