### ISSUE TITLE
Screen proportions on different users' screens

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#120]
During user testing, Simone noticed that one on user's screen the map and text were divided equally on screen (equal width), however, on another user's screen the map took up two thirds of the screen. 
Can we make this responsive so that it always shows the same proportions all size screens?

**Comment by fvanderbiest** [comment]
I think the issue comes from the fixed width icons raw.
This issue will become even more important when thor handles a greater number of hazards (land slide, ... ).

**Comment by ingenieroariel** [comment]
We need enough space in the description panel to show the text. I do not think having the same proportions in all screen sizes is that important as the tool being usable in all screen sizes.

My first reaction would be to consider this a non issue, but I think it would be good to paste here screenshots on different resolutions to agree on whether or not the tool is usable in those conditions.

Having the same behavior in all browsers and screens is a red herring and not a goal we should try to achieve, the goal should be to have a great user experience in all devices, it does not matter if it is the same user experience in all devices.

**Comment by fvanderbiest** [comment]
IMO, the  map size should not change when the browser window is redimensionned.
The map could probably be reduced to a fixed width and height div integrated in the report page.

**Comment by pgiraud** [comment]
Let's wait for user testing feedbacks. Closing.
