### ISSUE TITLE
Download PDF

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#122]
Ariel would like to have (on top of each other):
* 1 map for admin unit level 0
* 1 map for admin unit level 1
* 1 map for admin unit level 2 (if admin level 2 has been selected for report generation)

And for each hazard type, an additional map of selected location with hazard level

There's also the requirement to save every generated report on the server (or S3 ?) and have a permalink to it.

**Comment by stufraser1** [comment]
If a PDF report is required by a user some time after they issued it, could they submit a request on the basis of a reference to the saved report and request a copy from us via contact us or via a dedicated feature of the tool.

**Comment by nchauvin-brgm** [comment]
FYI, in case you don't check discussions on the project site:

The front cover mockup is available for download as a PDF file in the UX section.

It is made up of:

1. the ThinkHazard logo and baseline
2. the name of the selected location, followed by the name(s) of the parent administrative division(s), where appropriate 
3. the WB world map with a pin indicating the selected location
4. the hazard icons colored according to hazard levels
5. the PDF creation date and the corresponding online report URL

(3) I hope C2C will be able to place the pin at the correct location on the vector map. I see it as a big minimap.

(4) I think it can be interesting to provide all hazard levels right from the front cover. I used a new color scheme that is supposed to be color blind friendly (see issue #304). But it remains to be decided whether we will use it instead of the current one.

(5) I also think it is important for the user to know when the PDF was generated and, if need be, to be able to go back to the up-to-date online report with a simple click.

**Comment by stufraser1** [comment]
Excellent thank you, I'll take a look

Stuart

On Tue, 24 Nov 2015 15:34 Nicolas CHAUVIN <notifications@github.com> wrote:

> FYI, in case you don't check discussions on the project site:
>
> The front cover mockup is available for download as a PDF file in the UX
> section.
>
> It is made up of:
>
>    1. the ThinkHazard logo and baseline
>    2. the name of the selected location, followed by the name(s) of the
>    parent administrative division(s), where appropriate
>    3. the WB world map with a pin indicating the selected location
>    4. the hazard icons colored according to hazard levels
>    5. the PDF creation date and the corresponding online report URL
>
> (3) I hope C2C will be able to place the pin at the correct location on
> the vector map. I see it as a big minimap.
>
> (4) I think it can be interesting to provide all hazard levels right from
> the front cover. I used a new color scheme that is supposed to be color
> blind friendly (see issue #304
> <https://github.com/GFDRR/thinkhazard/issues/304>). But it remains to be
> decided whether we will use it instead of the current one.
>
> (5) I also think it is important for the user to know when the PDF was
> generated and, if need be, to be able to go back to the up-to-date online
> report with a simple click.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GFDRR/thinkhazard/issues/122#issuecomment-159306110>.
>
-- 
Stuart Fraser, PhD
Disaster Risk and Catastrophe Analytics Consultant
stufraser1@gmail.com
Skype: stu_fraser1
+44 (0)7455 048 044
uk.linkedin.com/in/stuartfraserdisasterrisk

**Comment by nchauvin-brgm** [comment]
The "About" page mockup is now available for download in the UX section.

It is made up of:

* "About Think Hazard!" section
* Logos of the team
* Disclaimer / Legal informations
* Link to www.thinkhazard.org

(1) This is the [current draft](https://docs.google.com/document/d/1XjHZIs9nnmMSrKkFJ6gx_ZYDHMFNaSWixcfYII_1rMQ/edit) of the website's "About" section, but I don't know whether it can be used as such in the PDF report. Instead of \<insert names\>, there should be the list of the hazard datasets providers whose data are actually used in the report (not all providers registered in the tool).
(2) I chose not to add the dataset providers' logos because we can't know whether every provider would have its own logo and would be able to provide it in the appropriate format. In my opinion, names are sufficient.
(3) I picked up the text from the publication « Understanding Risk / Producing Actionable Information / Proceedings from the 2014 UR Forum ». It will probably need to be adapted.

**Comment by stufraser1** [comment]
I like the PDF report front page, with the features provided.

I like the layout of the 'about' page too. Please use this layout for FAQs page
Please ensure 'governements' is corrected in the disclaimer.

Text should be updated to:
Think Hazard! is a new web-based tool enabling non-specialists to consider the impacts of disasters on new development projects. Users of Think Hazard! can quickly and robustly assess the level of river flood, earthquake, drought, cyclone, coastal flood, tsunami, volcanic ash, and landslide hazard within their project area to assist with project planning and design.

Think Hazard! is a simple flagging system to highlight the hazards present in a project area. As such, a user is only required to enter their project location – national, provincial or district name. The results interface shows a user whether they require high, medium or low awareness of each hazard when planning their project.

Think Hazard! also provides recommendations and guidance on how to reduce the risk from each hazard within the project area, and provides links to additional resources such as country risk assessments, best practice guidance, additional websites. Think Hazard! also highlights how each hazard may change in the future as a result of climate change.
Think Hazard! was developed by the Global Facility for Disaster Reduction and Recovery (GFDRR) Innovation Lab, in partnership with BRGM (French geological survey), Camptocamp and Deltares. Hazard datasets have been provided by UNISDR, Impact Forecasting, SSBN, PRACFI, The World Bank.
The tool code is open source, to encourage other users to adapt the tool to their needs. The code can be found at https://github.com/GFDRR/thinkhazard.

**Comment by stufraser1** [comment]
please can you also add to the dataset providers:
IVM-VU, and USGS

**Comment by nchauvin-brgm** [comment]
Thanks @stufraser1 for your feedback.

I have updated the "About" page with:
* "governments" correction
* text update
* dataset providers addition

Please refer to the file "PDF Report - About (update 20151202)" uploaded on the project site.

**Comment by fvanderbiest** [comment]
See http://thor-project.brgm.fr/system/files/upload/documents/ux/thor-pdf-report-20151207.pdf

**Comment by nchauvin-brgm** [comment]
I will update the file today. The new file name will be thor-pdf-report-20151209.pdf. Just for your information.

**Comment by nchauvin-brgm** [comment]
Sorry, the new file won't be available before tomorrow morning...

**Comment by nchauvin-brgm** [comment]
The full pdf report is now available on the project site (UX section). The file name is thinkhazard-barima-waini-20151210.pdf, as it could be when actually generated by the tool. Hope you'll like it.

**Comment by nchauvin-brgm** [comment]
We have noticed that the file has been renamed to *thor-pdf-report.pdf*. Maybe we should set a naming convention so that filenames be meaningful? What do you think of the above suggestion:

**thinkhazard-location-name-yyyymmdd.pdf**

With the date being the date of PDF generation.

**Comment by stufraser1** [comment]
that seems sensible to me. Please go ahead.

On Thu, 10 Dec 2015 at 11:25 Nicolas CHAUVIN <notifications@github.com>
wrote:

> We have noticed that the file has been renamed to *thor-pdf-report.pdf*.
> Maybe we should set a naming convention so that filenames be meaningful?
> What do you think of the above suggestion:
>
> *thinkhazard-location-name-yyyymmdd.pdf*
>
> With the date being the date of PDF generation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GFDRR/thinkhazard/issues/122#issuecomment-163677074>.
>
-- 
Stuart Fraser, PhD
Disaster Risk and Catastrophe Analytics Consultant
stufraser1@gmail.com
Skype: stu_fraser1
+44 (0)7455 048 044
uk.linkedin.com/in/stuartfraserdisasterrisk

**Comment by nchauvin-brgm** [comment]
I have uploaded an updated version of the PDF report template (20151211), in which links to hazard dataset providers are highlighted in blue. I have also added a white background on the "About" page in an attempt to remove the front page's map persistence. Tested successfully locally and on the project site on FireFox 40, Chrome 47, Internet Explorer 10 and Safari 5.1.7. It will have to be tested from the demo server to ensure it's still OK.

**Comment by nchauvin-brgm** [comment]
New version uploaded (same filename), with links enabled for team members, hazard dataset providers and further resources. Regarding the datasource providers, I used the following URLs, hoping they are the right ones:

* UNISDR: https://www.unisdr.org/
* Impact Forecasting: http://www.aon.com/impactforecasting/impact-forecasting.jsp
* SSBN: http://www.ssbn.co.uk/
* The World Bank: http://www.worldbank.org/
* IVM-VU: http://www.ivm.vu.nl/
* USGS: http://www.usgs.gov/

I didn't succeed in finding a Web page for PRACFI.

**Comment by stufraser1** [comment]
PCRAFI can be found at http://pcrafi.sopac.org/

On Fri, 11 Dec 2015 at 09:50 Nicolas CHAUVIN <notifications@github.com>
wrote:

> New version uploaded (same filename), with links enabled for team members,
> hazard dataset providers and further resources. Regarding the datasource
> providers, I used the following URLs, hoping they are the right ones:
>
>    - UNISDR: https://www.unisdr.org/
>    - Impact Forecasting:
>    http://www.aon.com/impactforecasting/impact-forecasting.jsp
>    - SSBN: http://www.ssbn.co.uk/
>    - The World Bank: http://www.worldbank.org/
>    - IVM-VU: http://www.ivm.vu.nl/
>    - USGS: http://www.usgs.gov/
>
> I didn't succeed in finding a Web page for PRACFI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GFDRR/thinkhazard/issues/122#issuecomment-163953840>.
>
-- 
Stuart Fraser, PhD
Disaster Risk and Catastrophe Analytics Consultant
stufraser1@gmail.com
Skype: stu_fraser1
+44 (0)7455 048 044
uk.linkedin.com/in/stuartfraserdisasterrisk

**Comment by nchauvin-brgm** [comment]
Thank you, Stuart. There was a mispelling in the name. Corrected.
