### ISSUE TITLE
About, FAQ & resources pages

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#123]
The "About" page presents GFDRR, and the companies working on the project

**Comment by elemoine** [comment]
Please provide more details when you get a change.

**Comment by stufraser1** [comment]
We would like to see the button for the resources page (on the header bar) be titled 'REsources', rather than 'References', which is currently is. Thank you

**Comment by pgiraud** [comment]
Duplicate. See #299.
