### ISSUE TITLE
User feedback, data suggestions

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#126]
The admin should be able to see the feedbacks and the permalink to the report which generated this user feedback

The user has access to a form to give feedback (related to a specific report)
The form should include an email field

**Comment by stufraser1** [comment]
Can we make the feedback button more prominent - indicating to the user that it is possible to provide feedback (by implementing an additional button called 'Feedback')

Will feedback allow users to make a free-form comment on one of a series of common topics (shown in a dropdown list)? Will the feedback be linked to page, location, and hazard that they were looking at when they placed the feedback?

We would like to draw users' attention in the beta version to the fact we are wanting feedback. Can we place a floating box that appears across the homepage, which states "This is a development Beta version. We are eager to receive feedback on the tool - please enter any feedback at the Feedback button" or an alternative industry standard message to this effect. The box should allow the user to click on an 'X' to close the box and continue into the tool.

**Comment by pgiraud** [comment]
See #290.
