### ISSUE TITLE
Back Office UI

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#130]
No need for it to be fancy, just functional for the admin guy (easy to use)

functions:
 - [ ] need to add new layers or new documents
 - [ ] create / Edit / Freeze recommendation and additional info
 - [ ] ask for recompute because hazard layer has changed (we don’t want it to happen automatically through MD) either whole world or single area
 - [ ] nice to have : see comments on reports -> through a map UI - heatmap to see where most comments are being created 
 - [ ] consult feedbacks
 - [ ] change thresholds

**Comment by pgiraud** [comment]
Not relevant anymore.
