### ISSUE TITLE
datamart sync process

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#132]
There should be a way to let the admin sync the datamart from the staging server to the production server, once he's happy with the outcome of the calculations.

**Comment by pgiraud** [comment]
Actually, we want:

 - a processing instance where processing happens and the admin user can see the result of the processing.
 - a public instance to which end users connect.

What needs to be done:
 - [ ] configure different databases url,
 - [ ] add script to publish data from processing to public instance,
 - [ ] visually distinguish processing instance,
 - [ ] restrict access to processing instance.
