### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#137]
Nicolas, could you generate a simple favicon for the site ? Or is it the GFDRR's responsibility ?

**Comment by nchauvin-brgm** [comment]
Usually, the favicon is based on the website logo. As we don't have a logo worthy of the name for the moment (graphic designer Miki Fernández should work on that), I suggest, in the meantime, to use GFDRR's (attached – please remove .png extension). 
![favicon ico](https://cloud.githubusercontent.com/assets/12515248/7813500/01da22d8-03bc-11e5-93a7-eadfd323c761.png)

**Comment by marionb** [comment]
See http://www.gfdrr.org/.
