### ISSUE TITLE
ol.js not found

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#14]
http://localhost:6543/lib/openlayers/dist/ol.js -> Not Found.

When installing the project, the `ol.js` built version of OpenLayers is not created.

**Comment by elemoine** [comment]
Could you please try to run `npm cache clean openlayers`? I had the same problem once, and it was due to a bad openlayers package in the npm cache.

**Comment by pgiraud** [comment]
It doesn't work for me.
There's no `dist` folder in `node_modules/openlayers`.
