### ISSUE TITLE
Style of Download and Overview buttons

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#151]
Use font-awesome for the icons

**Comment by marionb** [comment]
@pgiraud in the document that contains the styling details that you sent me, under point 9 and 11: what is meant with the hover=shadow: ...?

**Comment by pgiraud** [comment]
This means that they we need to add a drop shadow (box-shadow) when the user hovers the button with the cursor.

This means adding something like this in the less files (to be adapted):
```less
button:hover {
  .box-shadow(0px 0px 6px -1px rgba(0, 0, 0, 0.33));
}
```
