### ISSUE TITLE
Don't display legend nor caption in overview

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#165]
When no hazard type is selected, we shouldn't show the legend. Same for the caption (_Earthquake hazard level_ in the mockups)

**Comment by marionb** [comment]
Which is the legend and which is the caption that we should not show? If no hazard is selected I see the following 
![legend_caption](https://cloud.githubusercontent.com/assets/1460598/8454061/b00d9d26-1ffa-11e5-9e0d-3bd8d5c0cf81.png)

**Comment by pgiraud** [comment]
So this means that it's already taken into account. Closing.
This was an easy one.  ;-)
