### ISSUE TITLE
Overview button

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#183]
Hi @nchauvin-brgm,

I'd propose we remove the "overview" button when displaying the report overview (ie. when no hazard type is selected) instead of applying an "active" style to it.
What do you think?

**Comment by nchauvin-brgm** [comment]
Hi @pgiraud,
I'm OK if it is a hindrance to your work, but we'll have to test wether it is confusing for users to see this button disappear after clicking on it.
