### ISSUE TITLE
Items not centered on homepage

### ISSUE THREAD

**Issue by ingenieroariel** [GFDRR/thinkhazard#267]
<img width="900" alt="screen shot 2015-09-03 at 8 10 13 am" src="https://cloud.githubusercontent.com/assets/54999/9659015/3db347a8-5213-11e5-95f4-335bba215940.png">

The subtext below thinkhazard and the icons below the search bar are not centered

**Comment by pgiraud** [comment]
Actually, the icons are. The search field isn't.
