### ISSUE TITLE
Some countries do not appear

### ISSUE THREAD

**Issue by ingenieroariel** [GFDRR/thinkhazard#268]
For example Egypt does not appear

<img width="407" alt="screen shot 2015-09-03 at 8 11 48 am" src="https://cloud.githubusercontent.com/assets/54999/9659044/71c11962-5213-11e5-9b93-fb2b8e34c4ad.png">

Iran does not appear unless you type islamic

<img width="293" alt="screen shot 2015-09-03 at 8 12 23 am" src="https://cloud.githubusercontent.com/assets/54999/9659055/87c28d36-5213-11e5-83d4-93049584bfd0.png">

<img width="368" alt="screen shot 2015-09-03 at 8 12 38 am" src="https://cloud.githubusercontent.com/assets/54999/9659058/91e288f2-5213-11e5-8edf-a7c5bef6b683.png">

**Comment by pgiraud** [comment]
May be related to #265.
