### ISSUE TITLE
Text error

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#276]
Ahead of alpha 2 release, please can you update the following text, for hazard where there is no evidence (e.g., cyclone in morocco):
'In the are you have selected ther is no evidence of'
(change spelling of 'ther' to 'there')
Thanks

**Comment by pgiraud** [comment]
This has to be done by BRGM.

**Comment by stufraser1** [comment]
I've requested BRGM to do this, by email
