### ISSUE TITLE
Implement bold text in earthquake recommendations

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#277]
Please implement the following text in earthquake recommendations as bold:
'Planning decisions, project design, and construction methods should take into account the level of earthquake risk in your project. '

This should be done for Alpha 2, to illustrate that we highlight the important text
Thank you

**Comment by pgiraud** [comment]
This has to be done by BRGM by adding '<b>' tags in the corresponding field in the data.

**Comment by stufraser1** [comment]
I've requested BRGM to do this, by email
