### ISSUE TITLE
Consistent order of icons on all pages

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#278]
Please can you make the order of icons consistent on all pages, to help user find the icons as easily as possible?
Based on relative data availability and frequency that people consider each hazard, the order should be as follows, from left to right on the home page and on recommendations page header

This should also be the order for the vertical list on recommendations page, unless the vertical stacking of hazards is determined by whether data is available (i.e., hazards with available data appear at top), in which case please use the following order as a secondary order, after ordering by data availability.

Flood
Earthquake
Drought
Cyclone 
Storm Surge
Tsunami 
Volcanic Ash
Landslide

Many Thanks

**Comment by stufraser1** [comment]
Please could you update the home page to be consistent with the results pages. Currently the home page is in a different order. to that in the original issue
Many Thanks

**Comment by pgiraud** [comment]
Fixed via 121cf8424e59157b953853b8b95b1debd03c1e56
