### ISSUE TITLE
Inconsistency between map and recommendations

### ISSUE THREAD

**Issue by fjacon** [GFDRR/thinkhazard#282]
In Egypt, subregion Al Wadi/al Jadid
For Flood : Map is grey (NPR) but risk is low
See attached image
![alwadi](https://cloud.githubusercontent.com/assets/1583203/9869411/0e1873c2-5b84-11e5-9674-31e4dbd68d4c.png)

**Comment by pgiraud** [comment]
Indeed.

I'm afraid the map just shows what's in the database.
The administrative division Al Wadi/al Jadid (code 1169) has a category type of "LOW" for flood which matches the report detail.
There's only one administrative division below (code 15551). This division has a category type of "NPR" for flood which matches the map.
