### ISSUE TITLE
Drop-down box of placenames

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#284]
When entering a location name in the search box, only five options are shown; scroll through and you may never get to the one you intend to use.
E.g. If you type ‘Unit’ United States shows up, but if you only type 'Uni’ it is not on the the list, because Tunisia is returned higher in the list.  

The drop-down list would ideally show all (or at least more) locations that match the partial name that has been entered.

**Comment by nchauvin-brgm** [comment]
Maybe we could increase the number of suggestions... and/or review how suggestions are ordered.

In my opinion, the first suggestions should match exactly what you are typing. For example, if you type "Uni", the suggestions should be ordered like this: 1) **Uni**ted Arab Emirates; 2) **Uni**ted Kingdom; 3) **Uni**ted States of America; 4) **Uni**ted States Virgin Islands (U.S.); 5) **Uni**ty (South Sudan). Only then, if there is no exact match anymore, suggestions should *include* the term entered, like "T**uni**sia".

Priority should also be given to full location name suggestions. I have noted an inconvenience when dealing with short location names like "Sud" in Morocco. If you type "Sud", which is a full location name, "Sud, Morocco" doesn't show up, whereas partial location names do, like "**Sud**an" or "South **Sud**an" or "Centre-**Sud**, Burkina Faso".

**Comment by stufraser1** [comment]
Agreed, it makes sense that the order should be alphabetic, showing locations that begin with those letter first, then locations that contain those letters - and that it should show the admin 1/2 divisions in this logic, not after admin 0 partial matches

**Comment by pgiraud** [comment]
Is it still relevant?

**Comment by stufraser1** [comment]
The ordering of place names is still not sensible. Taking the 'uni' example
it still has places beginning with uni below places with uni in the middle
if the name

On Thu, 14 Jan 2016 08:48 Pierre GIRAUD <notifications@github.com> wrote:

> Closed #284 <https://github.com/GFDRR/thinkhazard/issues/284>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GFDRR/thinkhazard/issues/284#event-514980641>.
>
-- 
Stuart Fraser, PhD
Disaster Risk and Catastrophe Analytics Consultant
stufraser1@gmail.com
Skype: stu_fraser1
+44 (0)7455 048 044
uk.linkedin.com/in/stuartfraserdisasterrisk

**Comment by pgiraud** [comment]
This looks better now for the "uni" example.
I'm close this issue. Please reopen if you find an example of unexpected order in search results. In this case, we'll have to take relevance into account.

**Comment by stufraser1** [comment]
Thank you for the update to this. Viewing on the latest version of the code (the one that includes the dynamic pdf report), the list correctly presents country name first, then admin 1, then admin 2.

However, the order of the names within the same admin unit level are not as we would like.
Typing 'tun' returns in order: 'Wallis and Futuna', 'Tunisia', 
Typing 'Bali' returns in order: 'Balikesir, Turkey', 'Bali, Indonesia'
These should both be the reverse of what is shown. I.e., Tunisia should appear first because the typed letters match left(string, 3) not mid(string, 3).
Likewise, Bali matches the admin name exactly (I think this can be achieved by matching with the left(string,4) in the same way as for 3 letters).

Other good check examples are 'Gren', 'Mont', 'Au'

**Comment by pgiraud** [comment]
We changed the request. The results seem to be correctly ordered now.

**Comment by stufraser1** [comment]
Yes, this looks much better, thank you very much

On Fri, 4 Mar 2016 14:48 Pierre GIRAUD, <notifications@github.com> wrote:

> Closed #284 <https://github.com/GFDRR/thinkhazard/issues/284>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GFDRR/thinkhazard/issues/284#event-577863598>.
>
-- 
Stuart Fraser, PhD
Disaster Risk and Catastrophe Analytics Consultant
stufraser1@gmail.com
Skype: stu_fraser1
+44 (0)7455 048 044
uk.linkedin.com/in/stuartfraserdisasterrisk
