### ISSUE TITLE
Increase opacity in hazard overlay

### ISSUE THREAD

**Issue by ingenieroariel** [GFDRR/thinkhazard#285]
Because of two things:

1. When an admin area is on top of water and is red, the color looks purple.
2. The map looks a bit anemic and the color can spice it up.

Suggestion:

Make the default opacity level be the same (or close to) as when the mouse pointer is on top, and go solid for the mouseover instead. The thermometer is malawi, let's adjust it so we do not see anything purple.

**Comment by nchauvin-brgm** [comment]
Could you please check that the layer's opacity when inactive is actually set to 75%? It should also be 100% when hovered.
