### ISSUE TITLE
The search field on the report should not be empty

### ISSUE THREAD

**Issue by nchauvin-brgm** [GFDRR/thinkhazard#286]
After submitting the search request, the search field on the report should show the location name that has been selected on the previous page.
For example, if I type "Centre Sud, Morocco" on the front page...

![thor-search-field-01-front](https://cloud.githubusercontent.com/assets/12515248/10157525/19bc434a-668b-11e5-85b3-bea8393d42cf.png)

...then submit, the search field on the report is currently empty:

![thor-search-field-02-report](https://cloud.githubusercontent.com/assets/12515248/10157548/3f4ffdea-668b-11e5-8ff2-4706e59fbac8.png)

It would be better if we had the location name, like this:

![thor-search-field-03-report](https://cloud.githubusercontent.com/assets/12515248/10157647/0bc06928-668c-11e5-888c-f56fffa6dd7d.png)

**Comment by pgiraud** [comment]
I just tried to do so, but I see 3 disadvantages:
 - it duplicates information about the current location,
 - it doesn't tell the user that he/she can search for other locations,
 - it may not reflect user's search since it updates to the new location when navigating on the map.

**Comment by pgiraud** [comment]
Ping @nchauvin-brgm.

**Comment by nchauvin-brgm** [comment]
I think people are used to search engines retaining search terms after submit, like Google. Just as they know they can modify their search. The fact that it duplicates the name of the current location is not a disadvantage to me, as long as it remains discreet. And it will be useful if the minimized header feature is implemented, since it shows the location when the breadcrumb and the title are hidden. That's why I would like this request to be processed. The next user tests will then allow us to see whether this is convenient or not.

**Comment by pgiraud** [comment]
Won't fix for now. Please reopen if users complain.
