### ISSUE TITLE
Homepage subtitle text

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#288]
We require the subtitle text on homepage to be centre-aligned beneath the 'think hazard!' title. 
This should be done by 10th October, as we are required to showcase the tool to high level WB staff.

Please update the text content from 
"Identify the hazards in your project area and receive guidance on how to handle them" 
to 
“Identify natural hazards in your project area and understand how to reduce their impact”

**Comment by nchauvin-brgm** [comment]
Actually, it is not a bug, it is (really) a feature... C2C integrated the baseline the way I designed it in the mockup. I wasn't happy with the single or two centered lines and I found it better looking when arranged on two centered lines with negative and positive text indentations. To me, this "destructured" style was also in connection with the project topic. But OK...

**Comment by stufraser1** [comment]
I see the reasoning and design feature in this, however, GFDRR management
would really rather it was centred, so thanks for actioning this!

On Tue, 29 Sep 2015 at 16:37 Nicolas CHAUVIN <notifications@github.com>
wrote:

> Actually, it is not a bug, it is (really) a feature... C2C integrated the
> baseline the way I designed it in the mockup. I wasn't happy with the
> single or two centered lines and I found it better looking when arranged on
> two centered lines with negative and positive text indentations. To me,
> this "destructured" style was also in connection with the project topic.
> But OK...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GFDRR/thinkhazard/issues/288#issuecomment-144096893>.
>
-- 
Stuart Fraser, PhD
Disaster Risk and Catastrophe Analytics Consultant
stufraser1@gmail.com
Skype: stu_fraser1
+44 (0)7455 048 044
uk.linkedin.com/in/stuartfraserdisasterrisk

**Comment by nchauvin-brgm** [comment]
Sure, I will.

**Comment by stufraser1** [comment]
Nicolas and CampToCamp. Please can you update this text to be centred as a matter of urgency. It seems like a small issue, but Lana must present this tool to our board in the middle of the week commencing 26 October, and has stressed she wants this text centred.

Many Thanks

**Comment by pgiraud** [comment]
Hi @stufraser1,

I'll do it this morning.

**Comment by nchauvin-brgm** [comment]
Hi @stufraser1 and @pgiraud,
I have just uploaded the latest version of the front page background image so that @pgiraud can update it at the same time.

**Comment by pgiraud** [comment]
Text is now centered and background image is updated. Closing.

**Comment by stufraser1** [comment]
Thank you both, looks great

On Mon, 26 Oct 2015 at 08:38 Pierre GIRAUD <notifications@github.com> wrote:

> Text is now centered and background image is updated. Closing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GFDRR/thinkhazard/issues/288#issuecomment-151060282>.
>
-- 
Stuart Fraser, PhD
Disaster Risk and Catastrophe Analytics Consultant
stufraser1@gmail.com
Skype: stu_fraser1
+44 (0)7455 048 044
uk.linkedin.com/in/stuartfraserdisasterrisk
