### ISSUE TITLE
Feedback button required

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#290]
Please can you implement a more obviously labelled 'Feedback' button, in addition to a 'Contact Us' - so that users are more aware that they can provide feedback on the tool.
The feedback button should provide admin users with a note of which peril, location, and page the user has clicked to enter feedback, provide a dropdown list of the areas in which they would like to provide information, and a free-form comment box.
Items for the dropdown could include:
- I have a suggestion for recommendation or further information
- There is a problem with the map
- There is a problem with the recommendation
- The hazard levels do not appear to be correct

For the beta version, where we are particularly keen to obtain feedback, is it possible to have a floating box that appears on the homepage that alerts users to the fact we want feedback? It could include text along the lines of: "This is a development Beta version, we encourage you to enter feedback on your experiences with tool". The user could then click an 'X' to remove the box and continue into the tool

**Comment by nchauvin-brgm** [comment]
I have made a proposal for a small feedback form included in the detailed report template, at the bottom of the page: see corresponding mockup (update 20151204) on the project site. Hope this is what you expected...

**Comment by stufraser1** [comment]
This form is what we expected. I'm unsure of the placement at this stage - we will be able to assess this more clearly when we're using it online I think.

We do need to update the text though, to have less emphasis on errors! Please can you update to: 
'We welcome any suggestions for improvements to the tool, including suggestions of data, recommendations, or resources to include'
We would also like the name and email address to be optional, so we don't discourage critical feedback from people worried about being identified.

**Comment by nchauvin-brgm** [comment]
Sure, mockup updated (same link).

**Comment by pgiraud** [comment]
See #436.
