### ISSUE TITLE
Update to the vertical lines to left of recommendations paragraphs

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#291]
There is concern in the team that the current use of vertical lines coloured according to hazard at the left edge of recommendations paragraphs, look like MS Word revisions. Can we replace the vertical lines with a coloured bullet point, perhaps the same as that used for the 'Further resources' section?

**Comment by nchauvin-brgm** [comment]
In november conference call, it was decided that all recommendations have to be treated equal priority and that the colour of recommendations has to remain the same as that used for current hazard level (no colour priority as suggested in the remote user testing feedback). I'll replace the vertical lines with bullet points as requested by GFDRR.

**Comment by nchauvin-brgm** [comment]
I have replaced the vertical lines with square bullets in the latest mockup of the detailed report (update 20151204).
