### ISSUE TITLE
Placement of 'Overview' button

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#293]
Some of the team have found placement of the 'Overview' button to appear like it is too far from other text. @nchauvin-brgm  - is it possible to design an alternative placement, so that it sits directly beneath the location breadcrumb?

**Comment by nchauvin-brgm** [comment]
I am happy with your requirement because I wasn't, over time, fully satisfied with the placement either. I had planned to move it near the location breadcumb in a further version of the mockup. Is it OK if it sits directlty *beside* it (on the right side of the bar), and not beneath it ?

**Comment by stufraser1** [comment]
Perhaps we need to think about the placement a little more: The overview
button takes the user back to the screen with all hazards.
'Overview' doesn't really capture the purpose of the button, so by placing
it further away it becomes more ambiguous.
What are your thoughts on placing it closer to the hazard icons?
If we wanted it on the level with the location breadcrumb and 'download pdf
button, could we label it 'All hazards overview' or 'All hazards'?



On Tue, 29 Sep 2015 at 16:53 Nicolas CHAUVIN <notifications@github.com>
wrote:

> I am happy with your requirement because I wasn't, over time, fully
> satisfied with the placement either. I had planned to move it near the
> location breadcumb in a further version of the mockup. Is it OK if it sits
> directlty *beside* it (on the right side of the bar), and not beneath it ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GFDRR/thinkhazard/issues/293#issuecomment-144101261>.
>
-- 
Stuart Fraser, PhD
Disaster Risk and Catastrophe Analytics Consultant
stufraser1@gmail.com
Skype: stu_fraser1
+44 (0)7455 048 044
uk.linkedin.com/in/stuartfraserdisasterrisk

**Comment by nchauvin-brgm** [comment]
As suggested by Stuart and users (cf. remote user testing feedback), I'll place the overview button next to other hazards and rework it with a similar design. I'll create a new icon to avoid confusion with river flood hazard's.

**Comment by nchauvin-brgm** [comment]
The new button can be seen in the report overview (active state) and detailed report (inactive state) mockups (update 20151204). I will provide it in SVG format in the UX section of the project site.

**Comment by stufraser1** [comment]
This new button is much more intuitive and well placed. Thank you.

**Comment by nchauvin-brgm** [comment]
Overview SVG icon now available for download on the project site...
