### ISSUE TITLE
Homepage map background alignment

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#296]
@pgiraud @nchauvin-brgm 
Another issue on the homepage, regarding the map background that sits behind the search bar:
On Chrome browser, this appears centrally.
On Firefox, it appears to the left and so is misaligned with all of the other features, which remain centrally located.
see attached:

![think hazard firefox](https://cloud.githubusercontent.com/assets/12515042/10724622/e687ccea-7bbd-11e5-9fe6-bdc64edabbc0.png)
![think hazard chrome](https://cloud.githubusercontent.com/assets/12515042/10724623/e6882384-7bbd-11e5-81af-35f4d70dff04.png)

**Comment by pgiraud** [comment]
Hi @stufraser1, does it have to be fixed right now?

**Comment by stufraser1** [comment]
not right now

On Mon, 26 Oct 2015 at 08:47 Pierre GIRAUD <notifications@github.com> wrote:

> Hi @stufraser1 <https://github.com/stufraser1>, does it have to be fixed
> right now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GFDRR/thinkhazard/issues/296#issuecomment-151063711>.
>
-- 
Stuart Fraser, PhD
Disaster Risk and Catastrophe Analytics Consultant
stufraser1@gmail.com
Skype: stu_fraser1
+44 (0)7455 048 044
uk.linkedin.com/in/stuartfraserdisasterrisk
