### ISSUE TITLE
Please fix the search bar styling on the front page

### ISSUE THREAD

**Issue by nchauvin-brgm** [GFDRR/thinkhazard#298]
The spread value of the box-shadow property should be 10 px.
The border-radius value of the box-shadow property should be 5 px.
The background-color value under the search icon should be #d91f2c.
Thanks.

**Comment by pgiraud** [comment]
I'm sorry but as far as I know I cannot specify the box-shadow border-radius.

**Comment by nchauvin-brgm** [comment]
Sorry, I wanted to say "border" instead of "box-shadow". Border-radius of 5px, border-width of 10 px, border-color of #58595b and border opacity of 15%.
