### ISSUE TITLE
FAQ, About, References

### ISSUE THREAD

**Issue by fjacon** [GFDRR/thinkhazard#299]
Work in progress :

- [x] FAQ: https://docs.google.com/document/d/13dBQUzxYf75843Y2KEUHOryinvEj5QVER95FceHvNK8/edit

- [x] About: https://docs.google.com/document/d/1XjHZIs9nnmMSrKkFJ6gx_ZYDHMFNaSWixcfYII_1rMQ/edit

- [x] Resources: https://docs.google.com/document/d/18JI3OmHGYCos1geKfmal9wSqjMrhPgQei7fMTFc6zs0/edit?usp=drive_web

**Comment by pgiraud** [comment]
@fjacon Are you sure that this doesn't need to be done for beta1?

**Comment by nchauvin-brgm** [comment]
If I am not mistaken, the "References" link should be removed from the header bar, since its content has moved to the bottom of the "About" page. (See point 8 in Stuart's email dated 2 December.)

**Comment by pgiraud** [comment]
Good point. See #341.
