### ISSUE TITLE
Adjusted scrolling of overview page

### ISSUE THREAD

**Issue by nchauvin-brgm** [GFDRR/thinkhazard#303]
From remote user testing feedback:

*Ability to resize to fit on one screen when looking at top level info would be a help - being able to see the summary without having to scroll.*

We recall that the full summary is also viewable when looking at the navbar with icons.

I think there isn't much we can do, apart from reducing a bit font size and space around hazard names. I'll update the mockup to this end.

**Comment by nchauvin-brgm** [comment]
I have made some changes to the report overview page layout in order to bring the content a little more to the top of the screen:

* smaller top margin of the location name in the header bar (10 px less)
* vertical orientation of "hazard level" title
* smaller font size for hazard names (36 px -> 32 px)

The gain is about 40 px (roughly the height of a hazard row). To me, no more can be done without degrading the look and feel of the page.

**Comment by pgiraud** [comment]
Taken into account in https://github.com/GFDRR/thinkhazard/pull/318.
Vertical orientation of the "hazard level" title still needs to be done. May not be available for the beta1. Opening a new issue to address this.
