### ISSUE TITLE
Colour scheme not suitable for colour blindness

### ISSUE THREAD

**Issue by nchauvin-brgm** [GFDRR/thinkhazard#304]
A user found it hard to distinguish colours because of colour blindness (cf. remote user testing feedback). 

I picked the four colours (red, orange, yellow and gray) from the UR general style guidelines and I agree it might be sometimes difficult to distinguish orange from yellow when opacity is not full. I'll make a proposal with more saturated colour values, but I think it is important that we keep the red-orange-yellow-gray color scheme.

This issue is somehow linked to @ingenieroariel's issue #285: increase opacity in hazard overlay. In my opinion, we have to keep a minimum level of transparency in order to be able to see roads, rivers, water bodies, forests and relief under the hazard overlay. But maybe if we choose more saturated colours, it will solve this issue at the same time.

**Comment by nchauvin-brgm** [comment]
Here is a proposal for a new color scheme that I picked from the online [ColorBrewer](http://colorbrewer2.org/) tool (color advice for cartography). I chose the following criteria :
* Number of data classes: 4 (high, medium, low, very low)
* Nature of data: sequential (since data progress from very low to high level)
* Usability:
  * color blind friendly (in response to user's request)
  * color printing friendly (i guess the pdf report will be often printed)
  * photocopy friendly (there is also a possibility that the printed report will be photocopied)
  * laptop (LCD) friendly

The result is as follows:

**Color scheme**
![thor-color-scheme-01-color-palette](https://cloud.githubusercontent.com/assets/12515248/11333696/e14ddaee-91cf-11e5-9b36-e1766209833f.png)

**Map example with solid color**
![thor-color-scheme-02-solid-color-bg](https://cloud.githubusercontent.com/assets/12515248/11333779/99cbec50-91d0-11e5-885f-a228699e53e9.png)

**Map example with color transparency**
![thor-color-scheme-03-terrain-bg](https://cloud.githubusercontent.com/assets/12515248/11333800/b6657156-91d0-11e5-82ce-39d87337f6e4.png)

The only significant difference compared to the current color scheme is the color associated with the "very low" level: it would change from gray to light yellow. I think it is a good thing in the end, since it is recommended that the look of sequential schemes be dominated by lightness steps, with light colors for low data values to dark colors for high data values.

GFDRR team, are you happy with this new color scheme proposal?

**Comment by nchauvin-brgm** [comment]
There is a problem with the new color scheme proposal. The yellow and yellow-orange color are too light to be readable when they are used as text on a white background, and as background behind white text, as you can see on the screenshot:

![thor-color-scheme-issue](https://cloud.githubusercontent.com/assets/12515248/11555057/a31d2bfa-999d-11e5-9d0f-29e41e6ee84d.png)

Providing a solution by modifying the overall graphic design would be too complicated and time-consuming, and, since beta 1 deadline is close, I suggest to look for another color scheme that would be compatible and would not require any change other than color values.

I'm currently on it. My goal is to provide C2C with the updated mockups by the end of the day.

**Comment by nchauvin-brgm** [comment]
Here is a new color scheme proposal:

![thor-new-color-scheme-20151203](https://cloud.githubusercontent.com/assets/12515248/11563027/e3b937b0-99d1-11e5-8a47-f34017377201.png)

The red color comes from the UR style guide (and ThinkHazard! logo). The following colors are adjacent colors that I picked using a color wheel. We are fairly close to the original orange and yellow colors from UR's secondary color palette. Dark grey is used for the new "Overview" button, and light grey for hazards with no data, which are clickable from now on.

Regarding the color-blindness issue, I tested the colors with the [Vischeck tool](http://www.vischeck.com/), which shows what colors look like to someone who is color blind. I made a comparison between the current/previous color scheme and the new one. Here is the outcome:

# Current/previous color scheme
## Deuteranope (green color deficit, most common)

![thor-color-blindness-previous-color-scheme-deuteranope](https://cloud.githubusercontent.com/assets/12515248/11563517/a0810e5c-99d4-11e5-8800-3c0447a875f2.png)

![thor-color-blindness-previous-color-scheme-map-deuteranope](https://cloud.githubusercontent.com/assets/12515248/11564686/bfc475d2-99da-11e5-8840-047f64dd3dd4.png)

## Protanope (red color deficit, rare)

![thor-color-blindness-previous-color-scheme-protanope](https://cloud.githubusercontent.com/assets/12515248/11563583/0084ce1a-99d5-11e5-899e-54b20df9f40b.png)

![thor-color-blindness-previous-color-scheme-map-protanope](https://cloud.githubusercontent.com/assets/12515248/11564691/c8530fe2-99da-11e5-8e6e-b2c7e19864ac.png)

## Tritanope (very rare)

![thor-color-blindness-previous-color-scheme-tritanope](https://cloud.githubusercontent.com/assets/12515248/11563606/1b5a98fa-99d5-11e5-9543-38c768c28782.png)

![thor-color-blindness-previous-color-scheme-map-tritanope](https://cloud.githubusercontent.com/assets/12515248/11564698/d3a55d46-99da-11e5-9c03-cb06d6ef2e5e.png)

# New color scheme
## Deuteranope

![thor-color-blindness-new-color-scheme-deuteranope](https://cloud.githubusercontent.com/assets/12515248/11563620/2bbe1302-99d5-11e5-880d-74531ebc9d1b.png)

![thor-color-blindness-new-color-scheme-map-deuteranope](https://cloud.githubusercontent.com/assets/12515248/11564708/dc2fda5e-99da-11e5-97f7-62910464166d.png)

## Protanope

![thor-color-blindness-new-color-scheme-protanope](https://cloud.githubusercontent.com/assets/12515248/11563642/46f5c58e-99d5-11e5-80bd-c54b62a5aa2b.png)

![thor-color-blindness-new-color-scheme-map-protanope](https://cloud.githubusercontent.com/assets/12515248/11564716/e582037a-99da-11e5-8c74-c2e32b2462e0.png)

## Tritanope

![thor-color-blindness-new-color-scheme-tritanope](https://cloud.githubusercontent.com/assets/12515248/11563653/53b38838-99d5-11e5-8d55-d1464528cf0f.png)

![thor-color-blindness-new-color-scheme-map-tritanope](https://cloud.githubusercontent.com/assets/12515248/11564726/efe3ac1a-99da-11e5-9537-5166f881509e.png)

If the color-blindness issue was related to the grey-green color used for the very low level hazards, which may look close to the red color, using a sequential color scheme ranging from dark colors for highest levels to light colors for lowest levels (and data not available) should resolve this problem.

If there wasn't any color-blindness issue after all, please check that the opacity of the layers is actually set to 75% as in the mockups. If it was not the case, colors should then become more distinguishable from the background.

Here are the new color values:
* Dark grey (overview button): #58595b
* Red (high level): #d91f2d
* Orange (medium level): #df7120
* Yellow-orange (low level): #df9c20
* Yellow (very low level): #dfbb20
* Light grey (no data available): #d9d9d9

**Comment by nchauvin-brgm** [comment]
I have set up the new color scheme in the latest versions of the report overview and detailed report mockups. Please refer to the project site if you want to have a look at them.

After testing, if it turns out that theses colors are still not suitable, maybe we could consider having two distinct color schemes: one for the overall design (UR-related), the other specific to the map (first color scheme proposal), both being quite similar.

**Comment by stufraser1** [comment]
The colours in the new mockup look good to me. The addition of the hazard label is helpful for users struggling to differentiate colours on the map. Thank you

**Comment by pgiraud** [comment]
The colour scheme issue is fixed. Opening a new issue for the tooltip on map displaying level.
