### ISSUE TITLE
Update of search bar - required in alpha 2 version

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#306]
Please could we update the grey default text in the search bar from 'Ben Slimane' a more-commonly known location?
This could read 'Enter location... (e.g. Turkey, or Istanbul)'. 

We require this to be done in the alpha2 version as soon as possible, 

We have to share this with management this week to prepare for an internal review - management have fed back that the Ben Slimane example is somewhat confusing as they don't know immediately that it is the name of a location.

Many thanks
Stuart

**Comment by pgiraud** [comment]
I'll fix that one as soon as possible. Today hopefully.

**Comment by pgiraud** [comment]
Fixed.
