### ISSUE TITLE
Basemap resolution is super low for the city level

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/thinkhazard#34]
Searching for Ben Slimane, Morocco or Colombo, Sri Lanka, the background map/base layer is very low and show big pixels.

On a related topic, have we decided what the basemap would be?

**Comment by elemoine** [comment]
We use NaturalEarth for the moment. See https://github.com/GFDRR/thinkhazard/blob/master/doc/data.md#raster.

**Comment by pgiraud** [comment]
See #41.
