### ISSUE TITLE
About / FAQ - requires navigation function back to previous page

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#342]
Think Hazard icon on about / FAQ pages returns user to tool home page (requiring them to enter location and navigate to peril again). Please update the link for the icon to take them back to the previous page instead.

**Comment by nchauvin-brgm** [comment]
I have another suggestion, which is to open the About and FAQ pages on top of the current page in a lightbox. E.g.: http://fancyapps.com/fancybox/#examples. This way, the user just has to close the box to go back to the page he/she was on before.

**Comment by pgiraud** [comment]
@nchauvin-brgm Would a bootstrap modal work?

**Comment by nchauvin-brgm** [comment]
It sounds like a good idea.

**Comment by pgiraud** [comment]
@stufraser1 Can you please confirm that the lightbox/modal window is OK for you?

**Comment by stufraser1** [comment]
Sounds good
