### ISSUE TITLE
Mobile compatible front-end

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/thinkhazard#35]
I tried to access the website through a mobile phone and it doesn't work super well. Not a priority for now but I just wanted to make sure that the design and libraries used will allow to fix that later on

**Comment by elemoine** [comment]
Thanks for creating the issue. Yes, we do think about mobile, tablets and touch devices when designing and developing, but it is known that the tool does not yet work on these types of devices.

**Comment by pgiraud** [comment]
Won't fix.

**Comment by pgiraud** [comment]
I'm reopening this issue.
It's still not planned to take the mobile devices into account.
I'm leaving it open with no milestone. Should be considered as a future enhancement.

**Comment by stufraser1** [comment]
We are creating contract to enable this work, to follow completion of v2 development project. @fjacon Suggest closing this general issue and opening specific issues relating to that project, at the relevant time?

**Comment by fjacon** [comment]
@stufraser1 agreed
