### ISSUE TITLE
Allow alternate names for countries and cities.

### ISSUE THREAD

**Issue by ingenieroariel** [GFDRR/thinkhazard#362]
For example:
```
The United Kingdom is hard to find, since its name in the tool is ‘U.K. of Great Britain and Northern Ireland’. Can we change to United Kingdom (consistent with WB names)?
```

@ingenieroariel should provide a new column with alternate names to be used with the search.

**Comment by pgiraud** [comment]
@ingenieroariel anything new?

**Comment by pgiraud** [comment]
@ingenieroariel This is still relevant. Do you have anything to provide?

**Comment by ingenieroariel** [comment]
@pgiraud I believe the other improvements to search are enough. I'll talk to Stu in our next meeting and decide if we still want to do it.

**Comment by pgiraud** [comment]
So, let's close this issue for now. Feel free to reopen if appropriate.
