### ISSUE TITLE
Printing from Internet Explorer

### ISSUE THREAD

**Issue by ingenieroariel** [GFDRR/thinkhazard#363]
From our manager:

```If you print any of the website pages (Internet Explorer), it looks very strange on paper. The headings are totally mixed up. Not super urgent I would say, but Francis likes to print things.```

Do we allow printing arbitrary pages or should we instruct people to print the PDF instead? Are there any quick wins? i.e. a dedicated stylesheet for printing.

**Comment by stufraser1** [comment]
I guess this hasn't been solved, so we should point users to print the pdf? I can do this by adding an FAQ while updating those again today

**Comment by pgiraud** [comment]
Several months ago, before we decided to go with PDF generation, I tried to work on some browser printing using media queries.
https://github.com/GFDRR/thinkhazard/pull/166

Requires too much work to be done before final release though.
Something to add to the version 2 suggestions.

We may be able to display a warning message in the browser printed page. Would this be an option?

**Comment by stufraser1** [comment]
We provide a pdf print button, so lets leave it at that for now.

**Comment by pgiraud** [comment]
OK. Let's close this issue then.
