### ISSUE TITLE
geonode's distribution_url as hyperlink on the data source name

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#378]
To be done after https://github.com/GFDRR/thinkhazard/pull/343 is merged

**Comment by fvanderbiest** [comment]
As discussed with @pgiraud, this will first require that models from processing are merged into common.

**Comment by fvanderbiest** [comment]
related to https://github.com/GFDRR/thinkhazard/issues/361

**Comment by pgiraud** [comment]
Fixed with #394.
