### ISSUE TITLE
Map : Add the name of the data source at the bottom of the map

### ISSUE THREAD

**Issue by fjacon** [GFDRR/thinkhazard#40]

**Comment by elemoine** [comment]
I don't think this is alpha release material. Do we agree?

**Comment by ingenieroariel** [comment]
I agree, we should be able to deal with this at the beta stage.

**Comment by fvanderbiest** [comment]
This won't be ready for beta1, postponing to beta2.

**Comment by fvanderbiest** [comment]
With https://github.com/GFDRR/thinkhazard/pull/343, the hazardset name is displayed on hazardlevel hovering. Not exactly what was expected here, but this leaves room for longer hazardset names IMO.

What do others think about it ?

**Comment by pgiraud** [comment]
There's room under the map for this.
![Uploading Capture d’écran 2015-12-14 à 18.49.55.png…]()

**Comment by fvanderbiest** [comment]
OKay, I had not seen this page.

So, under the map, we'd like to have the links to the 3 layers that compose the hazardset. Unfortunately, there are several issues:
 * the hazardset id does not allow us to build links to the composing layers (eg: http://45.55.174.20/layers/hazard%3Apa2475krigclip cannot be inferred easily from hazard_set = "PA-EQ" or geonode_id = 221)
 * hazardsets and layers belong to another schema ("processing"), which does not reside on the same server

Two options:
 * either make Layers and Hazardsets part of the datamart schema
 * or put more extra data in the HazardCategory / AdministrativeDivision association.

I think I would favor option 1. Opinions ?

**Comment by fvanderbiest** [comment]
In the mean time, only the hazardset id is displayed under the map.

![capture du 2015-12-14 22 51 11](https://cloud.githubusercontent.com/assets/265319/11795107/3b0455cc-a2b5-11e5-85b9-e7de38d596db.png)

**Comment by fvanderbiest** [comment]
> I think I would favor option 1. Opinions ?

@pgiraud is OK, and @arnaud-morvan is implementing it.

**Comment by pgiraud** [comment]
Fixed via #385 and #394.
