### ISSUE TITLE
Updated units in GeoNode

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#403]
@ingenieroariel says: "Just a note that the units changed from PGA-g to PGA-g-dec and SA-g to SA-g-dec"

```
('SA-g-dec', _('Spectral Acceleration (g)')),
('PGA-g-dec', _('Peak Ground Acceleration (g)')),
('PGA-g-per', _('Peak Ground Acceleration (%g)')),
```

**Comment by fvanderbiest** [comment]
I guess geonode metadata need an update since they still refer to the old units.

eg: http://45.55.174.20/api/layers/?hazard_type__in=earthquake

**Comment by ingenieroariel** [comment]
Fixed.

```labs_geonode_metadata=# update base_resourcebase set hazard_unit = 'PGA-g-dec' where hazard_unit = 'PGA-g';
UPDATE 14
labs_geonode_metadata=# update base_resourcebase set hazard_unit = 'SA-g-dec' where hazard_unit = 'SA-g';
UPDATE 9
```

**Comment by fvanderbiest** [comment]
Thanks !
Should be adressed with https://github.com/GFDRR/thinkhazard/pull/404

We do not have thresholds related to SA-g / SA-g-dec for now.
