### ISSUE TITLE
Links to GeoNode in Data source

### ISSUE THREAD

**Issue by ingenieroariel** [GFDRR/thinkhazard#405]
Instead of having a lightbox, let's show owner__organization with link to GeoNode detail url (distribution_url ).

**Comment by stufraser1** [comment]
For a given map showing hazard levels, there will be a data owner listed below the map for each *dataset* used to derive the hazard levels. Within each dataset, there are a series of data *layers*. We cannot link to a dataset, because there is no geonode page that displays the dataset, there is only a link to each layer within the dataset. W also can't link to all layers using one hyperlink, so we need to choose a layer in the set, to link to. 

As a default, could the hyperlink be the URL of the layer used wth the highest return period?

**Comment by stufraser1** [comment]
Alternatively, this would be more intuitive to the user:
The portion of the layer name that is common to a dataset is derived based on the dataset used, and then the link to the geonode is compiled from that:
e.g., a map that shows Drought would use DR-GLOBAL-IVM-WCI-1000 as one layer in the dataset. The first part of the name (some or all of that) would be incorporated into a string representing the URL: http://45.55.174.20/search/?title__icontains=IVM-WCI&limit=100&offset=0
This takes a user to the geonode page that lists all layers matching that string.

**Comment by stufraser1** [comment]
@fjacon requested confirmation of how we would like to see the data source presented. To confirm:

1. Display owner__organization on the UI.

2. If multiple data sources used in mapping, display in comma separated list, or vertical list, to be decided by CampToCamp on the basis of functionality (i.e. can border around map be dynamically changed to accomodate a vertical list of >3 sources?

3. User to click/hover on displayed owner__organization, to display a box

4. Box to contain:
  a. 'Data owner': owner__organization.
  b. 'Link to data': distribution_url. This would be the link to the geonode page containing all data sets, if available in the metadata. If that is not included in metadata, this could be the data owner's website. If linking to Geonode, link to page that lists all layers in that dataset (for how this can be done, see my previous comment in this issue
  c. Intensity unit of hazard data.
  d. Comma separated list of return periods available in dataset

**Comment by pgiraud** [comment]
@stufraser1
Sorry to be a bit late on this one.
I finally started working on it.
I have questions about the content and the UI.

1. We have been using `distribution_url` for the link so far. In my opinion, this url is already the right place to determine if the user should be redirected to geonode or directly to the owner website. This url comes from geonode and should already be pointing to the correct location. In other words, I think it's IMO simpler to set this url (a bit manually) in geonode than to have a complex automatic system dealing with url in ThinkHazard.

2. The UI/UX may be perfectible.
 a. The box content is a bit too raw. Label names and layout could be improved.
![screenshot from 2016-03-08 14 26 32](https://cloud.githubusercontent.com/assets/319774/13602898/c8790328-e539-11e5-92ea-07960b2e7bc8.png)

 b. It's a bit weird that after clicking on a link labelled with "Owner name" a box with more details on the data source is opened. As a user, I expect to be redirected directly to a different website.
![screenshot from 2016-03-08 14 27 01](https://cloud.githubusercontent.com/assets/319774/13602909/d68a7802-e539-11e5-9050-f78fe6c44648.png)

Though I'm usually sensible to UI, I currently don't have any good idea to suggest. I'd appreciate any input. @nchauvin-brgm any suggestion?

**Comment by pgiraud** [comment]
One additional note about `distribution_url`: we can display it in the hazardsets page in the admin interface if it helps sanity check.

**Comment by nchauvin-brgm** [comment]
OK, I will address that UI/UX issue asap.

**Comment by stufraser1** [comment]
It would be helpful to show distribution_url in the hazardsets page, thank
you.
The alternative would be to just have the data source label hyperlink
direct to the box, but then we must find an alternative solution in case >1
data sources. as it is currently displayed, uaer can read on screen the
data sources too. This is important to keep. Lets leave it as it is
currently.

On Thu, 10 Mar 2016 14:25 Nicolas CHAUVIN, <notifications@github.com> wrote:

> OK, I will address that UI/UX issue asap.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GFDRR/thinkhazard/issues/405#issuecomment-194870647>.
>
-- 
Stuart Fraser, PhD
Disaster Risk and Catastrophe Analytics Consultant
stufraser1@gmail.com
Skype: stu_fraser1
+44 (0)7455 048 044
uk.linkedin.com/in/stuartfraserdisasterrisk

**Comment by stufraser1** [comment]
Also, the content looks fine to me, for the initial version. ariel and i
discussed showing abstract too, but felt it would be too much, when this is
available in the geonode

On Mon, 14 Mar 2016 10:43 Stuart Fraser, <stufraser1@gmail.com> wrote:

> It would be helpful to show distribution_url in the hazardsets page, thank
> you.
> The alternative would be to just have the data source label hyperlink
> direct to the box, but then we must find an alternative solution in case >1
> data sources. as it is currently displayed, uaer can read on screen the
> data sources too. This is important to keep. Lets leave it as it is
> currently.
>
> On Thu, 10 Mar 2016 14:25 Nicolas CHAUVIN, <notifications@github.com>
> wrote:
>
>> OK, I will address that UI/UX issue asap.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/GFDRR/thinkhazard/issues/405#issuecomment-194870647>.
>>
> --
> Stuart Fraser, PhD
> Disaster Risk and Catastrophe Analytics Consultant
> stufraser1@gmail.com
> Skype: stu_fraser1
> +44 (0)7455 048 044
> uk.linkedin.com/in/stuartfraserdisasterrisk
>
-- 
Stuart Fraser, PhD
Disaster Risk and Catastrophe Analytics Consultant
stufraser1@gmail.com
Skype: stu_fraser1
+44 (0)7455 048 044
uk.linkedin.com/in/stuartfraserdisasterrisk
