### ISSUE TITLE
handle climate change related documents

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#408]
In https://github.com/GFDRR/thinkhazard/issues/384#issuecomment-179786307 @stufraser1 says: 
Reports that are primarily related to climate change do not have a hazard type, as this is not currently an option in geonode (so hazard_type is empty). If this field must be populated, we can arrange to include climate change in a hazard_type field.

**Comment by fjacon** [comment]
@stufraser1 : can you confirm that these documents should appear in further resources for all kind of hazard type ? 
Could you provide an example ?
Also : it is too late to deal with this for beta 2.

**Comment by stufraser1** [comment]
They should appear for all hazards that have climate change statements
associated with them

On Wed, 17 Feb 2016 16:40 Frédéric Jacon, <notifications@github.com> wrote:

> @stufraser1 <https://github.com/stufraser1> : can you confirm that these
> documents should appear in further resources for all kind of hazard type ?
> Could you provide an example ?
> Also : it is too late to deal with this for beta 2.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GFDRR/thinkhazard/issues/408#issuecomment-185289481>.
>
-- 
Stuart Fraser, PhD
Disaster Risk and Catastrophe Analytics Consultant
stufraser1@gmail.com
Skype: stu_fraser1
+44 (0)7455 048 044
uk.linkedin.com/in/stuartfraserdisasterrisk

**Comment by stufraser1** [comment]
Has this been dealt with now, or will this now be something for version 2?

**Comment by pgiraud** [comment]
No, this hasn't been addressed. Unfortunately.

**Comment by stufraser1** [comment]
Revisiting this issue, climate change documents should be shown for RF, UF, CF, CY, DG, WF, EH.
Please confirm whether we should make CC documents appear in UI for >1 hazard by listing the first hazard in hazard_typefield then the rest in supplemental information, or whether it is possible to list 'climate_change' in supplemental information only, as we have done for several documents, e.g., http://45.55.174.20/documents/667/metadata

**Comment by pgiraud** [comment]
@stufraser1 The best to do is to comply with what has already been done for other documents. This means that a "primary" hazard should be given in the `hazard_type` field and other types in `supplemental_information`.
By doing it this way, the climate change documents should appear in the UI without changing a single line of code.

**Comment by stufraser1** [comment]
Noted.
