### ISSUE TITLE
Further resources related to regions

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#409]
A lookup table should be implemented to relate our countries (from the GAUL dataset) with those from GeoNode.

Reports for lower level administrative divisions should display the further resources related to their country.

**Comment by fvanderbiest** [comment]
@ingenieroariel do you think the relation between geonode regions and thor admin units should be 1-1 or 1-N ?

http://45.55.174.20/api/documents/359/ is linked with region 1 (the world) --> should this further resource appear in every EQ report ?

**Comment by fvanderbiest** [comment]
See https://github.com/GFDRR/thinkhazard/pull/427

**Comment by ingenieroariel** [comment]
I believe 1-N should be better. Because of things like Continent Names.

**Comment by pgiraud** [comment]
Fixed with help from @javierdaza.
