### ISSUE TITLE
Map : base map layer

### ISSUE THREAD

**Issue by fjacon** [GFDRR/thinkhazard#41]

**Comment by elemoine** [comment]
To be discussed. We currently use the highest resolution map of NaturalEarth.

**Comment by ingenieroariel** [comment]
I really like natural earth at the continent and country level. Can we use
for now something like Stamen Toner when we are below an specific zoom
level?

http://maps.stamen.com/toner/#11/10.9820/-74.8299

For the second iteration we can think better about designing a custom base
map.

-a

**Comment by elemoine** [comment]
@fvanderbiest, @pgiraud and discussed the « background layer » issue yesterday. Obviously, we agree that the resolution of the NaturalEarth layer is too low. We've identified five possible options:

1. Find another (possibly commercial) shaded relief layer
2. Generate our own shaded relief layer (TIF) from some DEM data
3. Generate our own shaded relief layer (TIF) from tiles (MapBox tiles for example)
4. Use a vector-based layer with no relief (using NaturalEarth shapefiles maybe)
5. Use tiles, from a tile web service (MapBox, OSM, …)

After discussion, we think that 5. is the most straightforward path. It is also the most flexible, as we can use OSM now, and switch to another, better looking, layer at any time in the future. This would mean adding OpenLayers back but that is not an issue at all.

**Comment by fvanderbiest** [comment]
Related to this issue, Nicolas says elsewhere:

```
Would it be possible to use tiles from MapQuest Open?

It seems that two free tilesets are available:
 * MapQuest-OpenStreetMap Tiles (mentioned by Stuart)
 * MapQuest Open Aerial Tiles (base map used in this html template)

Maybe we could use a different "look" by administrative division level, so that we are able to identify the level of administrative division just by looking at the map?

For example :
 * Level 0, MapQuest Open Aerial : http://mapq.st/1F6qDHC (or current base map, which seems to be Natural Earth)
 * Level 1, MapQuest OpenStreetMap : http://mapq.st/1KI7gGd
 * Level 2, MapQuest OpenStreetMap : http://mapq.st/1FjOiHP
```

**Comment by ingenieroariel** [comment]
I will talk to the guys at Mapbox to see if we can use mapbox streets.

**Comment by ingenieroariel** [comment]
Actually, now that I think about it ....

Since we have a fixed set of viewports, we can look into adapting OSM
bright for mapnik and just cache all the potential requests in ram or disk.
I believe at that zoom level the shaded relief can be optional (but we
should discuss it next week).

For the alpha, I think it is okay to leave the admin2s at a low resolution.

**Comment by fvanderbiest** [comment]
> Since we have a fixed set of viewports

At first, I thought this was very interesting from an IT perspective (since this would mean generating ~ 41k static images --as many as there are admin divisions-- that could be hosted on any CDN).
But we miss something here: the image dimensions depend on the screen resolutions, browser sizes, etc

There are other drawbacks too: 
 * it's not as flexible as a changing a layer's url in a config file
 * it requires an OSM db and a dedicated process to regenerate those thousands of tiles on demand

**Comment by fvanderbiest** [comment]
> I think we currently use the highest resolution map of NaturalEarth.

The [doc](https://github.com/GFDRR/thinkhazard/blob/master/doc/data.md#raster) does not say this.
We're currently using the LR (low res) version of the file. I'm experimenting with the HR dataset from http://www.naturalearthdata.com/downloads/10m-raster-data/10m-natural-earth-2/ to see if this can be improved for the user testings.

**Comment by fvanderbiest** [comment]
Nice try, but nope, this does not fix the issue for the smallest areas.

LR:
![capture du 2015-05-15 23 01 24](https://cloud.githubusercontent.com/assets/265319/7661818/5b777156-fb56-11e4-8936-315f7b95ee0b.png)

HR:
![capture du 2015-05-15 22 59 49](https://cloud.githubusercontent.com/assets/265319/7661804/2d13c42c-fb56-11e4-905e-56bce8e3aa2c.png)

**Comment by fvanderbiest** [comment]
Current ideas:
 * use "mapbox streets" slightly faded ($$ or agreement with GFDRR ?)
 * use mapquest open (for free)
 * rendering chain from osm db

**Comment by fvanderbiest** [comment]
Point 3 would let us use local projections (eg: EPSG:2154 for France), but we agreed to say that building a custom map background was not in the scope of the project for now.

**Comment by fvanderbiest** [comment]
Let's start with "mapbox streets" with a free plan at first.

**Comment by elemoine** [comment]
Using local projections sounds like a crazy idea to me…

**Comment by fjacon** [comment]
i think we agreed not doing that.

2015-05-20 15:36 GMT+02:00 Éric Lemoine <notifications@github.com>:

> Using local projections sounds like a crazy idea to me…
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GFDRR/thinkhazard/issues/41#issuecomment-103891615>.
>



-- 
Frédéric Jacon
Responsable d'agence - Chef de projets
Camptocamp France
Savoie Technolac
BP 352
48 avenue du Lac du Bourget
73372 Le Bourget du Lac, Cedex
www.camptocamp.com

+33 614 71 28 24 (mobile)
+33 458 48 20 38 (direct France)
+33 458 48 20 00 (standard)
+33 458 48 20 10 (fax)

**Comment by ingenieroariel** [comment]
Yep, the local projections idea went out the window quite fast.

:+1: on using Mapbox Streets, starting with the free tier.

-a
