### ISSUE TITLE
Hosting user guide document (PDF)

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#414]
Where do we host the PDF that contains the user guide? 
We need to provide users with a link to it in About and FAQ pages (there are placeholder links there now, linking to homepage). 
So, this would be hosted on github? - could we set up a 'dummy doc' that we can replace with final user guide (methodology document), once it is complete?

**Comment by fvanderbiest** [comment]
> this would be hosted on github

Why not ...

**Comment by stufraser1** [comment]
@pgiraud @fvanderbiest 
Please can you host these two pdfs on the github repository today, and provide the link to me?

For the method doc, please upload this draft version, so I can include a link to it in the FAQ, which need updating today aswell. We can update this draft version on github at the same link as soon as Nicolas has finalised the method report.

[SanityCheck All hazard summary - 20160428.pdf](https://github.com/GFDRR/thinkhazard/files/240251/SanityCheck.All.hazard.summary.-.20160428.pdf)

[test-pdf-TH-method.pdf](https://github.com/GFDRR/thinkhazard/files/240248/test-pdf-TH-method.pdf)

**Comment by NicolasT-brgm** [comment]
I have uploaded the final version of the document. I am waiting for two minor confirmations before saving it as pdf.
Do you plan to host the sanity check report also (not only the summary)?

**Comment by NicolasT-brgm** [comment]
uploaded on the collabrative space (sorry it is not explicit in the last post)

**Comment by stufraser1** [comment]
I think we can keep the sanity check report internal for now.

**Comment by NicolasT-brgm** [comment]
pdf report (signed): http://thor-project.brgm.fr/system/files/upload/documents/data/thinkhazard-methodology-report_v1_8final.pdf?download=1
word: http://thor-project.brgm.fr/system/files/upload/documents/data/thinkhazard-methodology-report_v1_8final_1.docx
report is ready for hosting on github

**Comment by stufraser1** [comment]
OK, now that the method is final please can you host *these* two pdfs on the github repository today, and provide the link to me?
Thanks!

[thinkhazard-methodology-report_v1_8final.pdf](https://github.com/GFDRR/thinkhazard/files/240575/thinkhazard-methodology-report_v1_8final.pdf)

[SanityCheck All hazard summary - 20160428.pdf](https://github.com/GFDRR/thinkhazard/files/240576/SanityCheck.All.hazard.summary.-.20160428.pdf)

**Comment by pgiraud** [comment]
Documents have been added to the application code.
Links to use in the FAQ page should look like the following (to be adapted).

```html
<a href="{{'thinkhazard:static/documents/thinkhazard-methodology-report_v1_8final.pdf'|static_url}}" target="_blank">Link</a>
<a href="{{'thinkhazard:static/documents/SanityCheck.All.hazard.summary.-.20160428.pdf'|static_url}}" target="_blank">Link</a>
```

**Comment by stufraser1** [comment]
Updated in FAQ file
