### ISSUE TITLE
admin unit naming: Jammu and Kashmir

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#418]
@ingenieroariel 
The state of Jammu and Kashmir (India) does not show up in India, but can be searched as 'Jammu and Kashmir' and shows up on its own. This is obviously due to the underlying geocode data, but it has been flagged to us by reviewers as being incorrect. What are your thoughts on adjsuting this, so that it appears as part of India? 
Adjusting this now would likely avoid feedback later about this issue

**Comment by ingenieroariel** [comment]
This is a side effect for the 'fix' we introduced to not get 'Reunion'
showing up when searching for France. Although in this case it seems to
have to do with disputed borders.

Let's ask internally and circle back here once we have a recommendation.

**Comment by stufraser1** [comment]
@ingenieroariel Did you find a solution for this?

**Comment by ingenieroariel** [comment]
@stufraser1 Should we just show all disputed borders in both sides of the dispute?

**Comment by stufraser1** [comment]
Could be a good solution to show all. Easily done?

On Fri, 13 May 2016, 23:21 Ariel Núñez, <notifications@github.com> wrote:

> @stufraser1 <https://github.com/stufraser1> Should we just show all
> disputed borders in both sides of the dispute?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/GFDRR/thinkhazard/issues/418#issuecomment-219173368>
>
-- 
Stuart Fraser, PhD
Disaster Risk and Catastrophe Analytics Consultant
stufraser1@gmail.com
Skype: stu_fraser1
+44 (0)7455 048 044
uk.linkedin.com/in/stuartfraserdisasterrisk

**Comment by stufraser1** [comment]
I am following up with WB to check the official stance on disputed territories in order to confirm whether I can duplicate J&K an attribute one instance to Pakistan and one to India (so that J&K shows in each country when queried)

**Comment by stufraser1** [comment]
I will adapt the GAUL data, accoridng to WB guidance, and issue an updated GAUL dataset
