### ISSUE TITLE
Download fails to identify some already cached layers

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#429]
`make download` sometimes fails to identify that a given layer is already in cache, eg:
```
INFO - Downloading layer CF-ID-IVM-100
INFO -   File s100.tif found in cache
INFO - Downloading layer CF-VN-SSBN-100
INFO -   Retrieving http://45.55.174.20/uploaded/layers/vn_1in100_JaN7A6i.tif
```
... but `vn_1in100_JaN7A6i.tif` already exists in my cache.

**Comment by arnaud-morvan** [comment]
Maybe you should rebase on master, when data_update_date is null we now set an very old date intead of now().

**Comment by pgiraud** [comment]
Not reproducible. Closing.
