### ISSUE TITLE
Grey-out the peril icons for ...

### ISSUE THREAD

**Issue by fjacon** [GFDRR/thinkhazard#44]
Grey-out the peril icons for which there are no data (Nicolas will update the mock-ups for this)

**Comment by fvanderbiest** [comment]
Should we make them unselectable too ?

**Comment by fjacon** [comment]
yes

2015-05-11 16:31 GMT+02:00 François Van Der Biest <notifications@github.com>
:

> Should we make them unselectable too ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GFDRR/thinkhazard/issues/44#issuecomment-100926707>.
>



-- 
Frédéric Jacon
Responsable d'agence - Chef de projets
Camptocamp France
Savoie Technolac
BP 352
48 avenue du Lac du Bourget
73372 Le Bourget du Lac, Cedex
www.camptocamp.com

+33 614 71 28 24 (mobile)
+33 458 48 20 38 (direct France)
+33 458 48 20 00 (standard)
+33 458 48 20 10 (fax)

**Comment by fvanderbiest** [comment]
Related PR is https://github.com/GFDRR/thinkhazard/pull/103
