### ISSUE TITLE
Regions only include countries

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#441]
With the pull request https://github.com/GFDRR/thinkhazard/pull/427, we can now link regions (as set in geonode) to GAUL administrative divisions.
In the .csv file provided by @javierdaza, only the regions that correspond to a country in GAUL are listed. We also need to link regions that are not countries to GAUL codes.

For example for Europe, we need as many lines in the CSV as countries in Europe (one for France, one for Spain, etc...)

First Header | Region id | GAUL code
------------ | -------------| --------
Europe | 5 | 85
Europe | 5 | 229
... | ... | ...

Does it make sense? Are you able to extract such information?

cc @ingenieroariel

**Comment by javierdaza** [comment]
Got it. It makes sense.
