### ISSUE TITLE
Front page

### ISSUE THREAD

**Issue by fjacon** [GFDRR/thinkhazard#46]
- [ ] Implement the response from the mock-up when there are no data available
- [x] The background colour for the secondary menu (top of the front page) should be transparent
- [ ] Use a different example to 'Ben Slimane' because this example does not work as it seems to be a city

**Comment by pgiraud** [comment]
No data available:
@elemoine do the search engine already know whether there's data or not for each result?

Search example:
@fjacon it looks like "Ben Slimane" is a administrative division in Morocco. Then I think it's a good example.

**Comment by elemoine** [comment]
> No data available:
> @elemoine do the search engine already know whether there's data or not for each result?

No, and I think adding that would have an impact on the search performance. I would not treat that issue for now.

**Comment by pgiraud** [comment]
Addressed in several other issues. Closing.
