### ISSUE TITLE
change feedback form URL

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#462]

**Comment by pgiraud** [comment]
@stufraser1 In order to anticipate the switch to production, can you please create (or at least copy) the google form used for user feedbacks.
We'll need to change the url in order not to continue pointing to the document I created during the development phase.

**Comment by stufraser1** [comment]
OK, I'll do this one too

**Comment by stufraser1** [comment]
I've set up a gfdrr labs google account to host the form. Can you copy/share the form to that account so we dont have to recreate it? Not sure if this can be done, but a suggestion on how to do this:
https://productforums.google.com/forum/#!topic/docs/jBHUFXytmPA
Account is gfdrrlabsthinkhazard@gmail.com

**Comment by pgiraud** [comment]
@stufraser1 
It looks like I cannot change the owner of the form directly since I created it using my camptocamp account.
However, I was able to create a copy with my gmail account. Then I changed the ownership of the copy. You should have received a notification.

I'll delete the initial version of the feedback form to avoid possible confusion or at least change the name and content temporarily.

**Comment by pgiraud** [comment]
@stufraser1 
It looks like I cannot change the owner of the form directly since I created it using my camptocamp account.
However, I was able to create a copy with my gmail account. Then I changed the ownership of the copy. You should have received a notification.

I'll delete the initial version of the feedback form to avoid possible confusion or at least change the name and content temporarily.

**Comment by pgiraud** [comment]
New form id to be used when we go in production: 1dhUO2ZsVEq86IslGVqTctANe3YY08a_mb08_ExhOqNw

We need to ensure that the prefilled parameters still match.

**Comment by stufraser1** [comment]
Thanks, I have access to that through the lab google account, and I'm documenting it all to go into the admin workflow document. We can only check that prefilled parameters match when we go to the final version?

**Comment by pgiraud** [comment]
Everything looks OK.
