### ISSUE TITLE
Add World Bank logo

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#490]
Please could you add this WB logo to the About page, in line with BRGM, Deltares and CamptoCamp logos.
Thank you

[WBG_Horizontal_Color.zip](https://github.com/GFDRR/thinkhazard/files/168032/WBG_Horizontal_Color.zip)

**Comment by nchauvin-brgm** [comment]
Here is the SVG version : [logo-wbg.zip](https://github.com/GFDRR/thinkhazard/files/168654/logo-wbg.zip).
