### ISSUE TITLE
Draw inspiration from the Global Flood Analyzer

### ISSUE THREAD

**Issue by ingenieroariel** [GFDRR/thinkhazard#5]
The url is: http://floods.wri.org/

**Comment by ingenieroariel** [comment]
Great things:

 - Selection by country (admin0) and state (admin1).
 - Map based interface
 - Clean(ish) urls that are updated after click: http://floods.wri.org/#/country/52/Colombia
 - Simplified polygons
 - Fast

![colombia](https://cloud.githubusercontent.com/assets/54999/6559075/72f0c13a-c64e-11e4-8975-85e1430ed726.png)

Bad things:

 - Too much polygon simplification, it is not updated on zoom in and greatly misrepresents the limits (my city ended up being outside of my admin1 boundary in the screenshot below).
 - Poor unicode handling (could not handle accents).
 - Unintuitive way to switch from 'by country' to 'by state'.
 - Naming ADMIN1 a state could be a misnomer, in my country the State is the country and the admin1 is a Department.

![atlantico](https://cloud.githubusercontent.com/assets/54999/6559079/79928686-c64e-11e4-9f44-26ad25425f20.png)

**Comment by ingenieroariel** [comment]
Just leaving this here for posterity, it can be closed as soon as the person in charge of defining the UI for the country selector takes a look at it.

**Comment by elemoine** [comment]
> Just leaving this here for posterity, it can be closed as soon as the person in charge of defining the UI for the country selector takes a look at it.

You probably want to ping the BRGM team, as I'm not sure they're watching the GitHub repo.

**Comment by ingenieroariel** [comment]
Will link to this in my next message to them. Closing.
