### ISSUE TITLE
Google analytics account

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#513]
@stufraser1 In order to anticipate the switch to production, can you please create a google analytics account?
I'll create one for development purpose but we'll need to have an official one when going live.
Thanks.

**Comment by stufraser1** [comment]
I will look into this

**Comment by stufraser1** [comment]
@pgiraud can we have a call today, friday, to talk about this issue and transfer of existing google form to my account?

**Comment by stufraser1** [comment]
@pgiraud 
I set up an analytics account
UA-75301865-1
google analytics tracking code to paste onto website

**Comment by stufraser1** [comment]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-75301865-1', 'auto');
  ga('send', 'pageview');

</script>
