### ISSUE TITLE
Error in Additional Information links

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#517]
The link, when clicking on additional information returns an error
e.g.,  http://45.55.174.20/documents/349/download
returns:
"ValueError at /documents/349/download
The 'doc_file' attribute has no file associated with it."

I believe this link should be 
http://45.55.174.20/documents/349
to take the user to the Geonode page for that document

@ingenieroariel Is this a field that is autopopulated by Geonode?

**Comment by stufraser1** [comment]
@ingenieroariel can you respond to this please

**Comment by stufraser1** [comment]
@fjacon Is the '/download' part of the link added in TH! ? 
I searched the metadata and couldn't find this full path in the geonode metadata. So, I can't adjust in Geonode

**Comment by pgiraud** [comment]
Indeed we construct the url using `document/ID/download`. It works on most cases but not all.
Do you want the link to point to the geonode document page?

**Comment by stufraser1** [comment]
Yes, please make the link point to the geonode document page, so that all work correctly.
