### ISSUE TITLE
Problem with admin divisions covering too much ground

### ISSUE THREAD

**Issue by elemoine** [GFDRR/thinkhazard#52]
Multipolygon divisions that span a lot of ground on the earth lead to non-relevant maps. (See [France](http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/thinkhazard/wsgi/report?divisioncode=85) for example).

We need to find a way to handle these (potentially numerous) cases.

**Comment by fjacon** [comment]
GFDRR will provide bounding box for all admin division level 0.

**Comment by elemoine** [comment]
How would that help?

**Comment by fjacon** [comment]
for example : BBox for france will prevent having bbox including la
réunion, guyane etc.

2015-05-20 15:40 GMT+02:00 Éric Lemoine <notifications@github.com>:

> How would that help?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GFDRR/thinkhazard/issues/52#issuecomment-103892398>.
>



-- 
Frédéric Jacon
Responsable d'agence - Chef de projets
Camptocamp France
Savoie Technolac
BP 352
48 avenue du Lac du Bourget
73372 Le Bourget du Lac, Cedex
www.camptocamp.com

+33 614 71 28 24 (mobile)
+33 458 48 20 38 (direct France)
+33 458 48 20 00 (standard)
+33 458 48 20 10 (fax)

**Comment by fvanderbiest** [comment]
Ariel, we need the extra geometries that you said Ana would prepare for us. Thanks.

**Comment by ingenieroariel** [comment]
I'm on the hook for this one. The good news is that the new admin dataset that we got GAUL already has Reunion and other territories split out. I will post here next week after more testing ...

**Comment by pgiraud** [comment]
@ingenieroariel What's the status on this issue?

**Comment by pgiraud** [comment]
Fixed. We're now using GAUL data.
