### ISSUE TITLE
Add a sitemap

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#521]
Sitemap should contain the list of url to countries overview report.
Then page should coutain (hidden) links to sub-divisions pages.

See #118.

**Comment by arnaud-morvan** [comment]
Wikipedia says (https://en.wikipedia.org/wiki/Sitemaps) that sitemap is limited to 10Mo or 50 000 url.
And actually we have 41948 divisions. So it should be possible to put all links in one sitemap.
It is also possible to use sitemap index.

**Comment by pgiraud** [comment]
You said that we're limited to 50000 urls but you limited the sitemap to countries. Is it on purpose?
