### ISSUE TITLE
use the cache-control header

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#528]

**Comment by pgiraud** [comment]
We should investigate the usage of the `Last-modified` header which should correspond of the last publish date.

**Comment by arnaud-morvan** [comment]
If I correctly understand, we could add a main ``public_app`` ot ``app`` table with one record containing metadata like publication date and time. This date would be added in response as ``Last-modified`` header.

When the client request the page, another header would be present in request and we could test if we have a more recent publication date. If not, we could respond with a ``304 Not Modified`` status and we do not need to get data and create a full response with 200 status.

This should not apply on admin pages, not that we should not have publication date in admin database.

**Comment by arnaud-morvan** [comment]
I also notice that like for maintenance page, a tween factory could be use to apply this on all pages.

**Comment by arnaud-morvan** [comment]
A more flexible solution could be a view decorator, applied on on views on which that we want to use this header.

I also notice that this could have effect on PDF requests. And this question comes : do we need respond a fresh pdf if no publication occurs since last one.

**Comment by arnaud-morvan** [comment]
See this for example : f0d12d40e61108c8a6d8d0dbc8d3cb67f2b90fe7
Not that for assets pyramid recomment using cacheburst.

**Comment by arnaud-morvan** [comment]
Fixed by #541
