### ISSUE TITLE
Archive database

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#530]
Each time the data is published, the public database should be archived.
We need to define how the archive should be done.
Creating a dump each time the data is published doesn't seem to good solution since 95% of the data is similar from one version to an other. Instead, we should investigate the usage of `barman`.

**Comment by arnaud-morvan** [comment]
After some reading on this, I learn that : 

PostgreSQL have a continuous archiving system : http://www.postgresql.org/docs/9.4/static/continuous-archiving.html
This permit to have a base backup (can be not consistent) and a transation log (called WAL). With this it is possible to recover any state of the database at any time. This is not exactly what we need, we only want to keep state of the database at publish time, not the full transaction log.

Barman propose an incremental solution, base on rsync and filesystem hard links to share files that do not change between consecutive backups. This seems to respond precesely to our needs. http://docs.pgbarman.org/release/1.6.0/#incremental-backup

So it should be possible, in publish script, to backup the processing database locally (main purpose of barman is to backup remotely), in a incremental cluster. After that, publishing will recover that backup on public consultation database.

**Comment by arnaud-morvan** [comment]
I note that barman make server backups and not database backups. After publication, all files for public database should have change.

**Comment by pgiraud** [comment]
Due to low frequency of archives, the low price of disk usage and the amount of work needed. We'll go for a complete archive of the database.

**Comment by arnaud-morvan** [comment]
Agree with you, barman seems to be a very interesting product, but it should be complicated to use here, it would imply a learning curve, and it seems to not correspond exactly to what we need (server and not database backups).
