### ISSUE TITLE
Detailed recommendation

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#546]
Additional detailed text should be available for users for each technical recommendation.
A "more information" link should be added in the UI. Clicking on the link should open a modal window.

**Comment by pgiraud** [comment]
First of all, I should verify the feasibility of storing the detailed text (with line breaks and bullet points) in the csv import file.

**Comment by pgiraud** [comment]
This should be done using an alembic migration script.

**Comment by pgiraud** [comment]
I've set up a demo in the integration server for the detailed text for recommendation.
Can you please give it a quick try before I merge?
http://int.thinkhazard.org/admin
Ping @NicolasT-brgm @stufraser1

**Comment by stufraser1** [comment]
@pgiraud 
I've tested this by pasting in some text direct form word document. The text has bullets and line breaks, which are not respected in the pop-up window in the tool.

The admin side workflow works well, and I like that the additional link shows only when the detailed text is available.
You'll see my example below, as it appears in UI for Indonesia Tsunami, http://int.thinkhazard.org/admin/preview/report/116-indonesia/TS

Detail text test CONTEXT:

• Around the world there is increasing recognition that avoiding development in the most frequently tsunami (or river flood or storm surge) inundated areas is one of the most effective means of managing future losses to natural hazards. Therefore, the planning for new developments should include consideration of already-existing national or regional regulations and guidelines • Many countries have some form of formal legislation, regulation or guidance for tsunami risk mitigation. These may broadly cover such aspects as: o Land-use planning, controlling the location of development for all or some types of building or project o Warning, through natural signs (earthquake, ocean disturbance), local initiatives and/or Tsunami Warning Centres o Response planning, usually focussed on life safety, evacuation routes, signage and safe locations o Public alerting mechanisms such as mobile phone apps, sirens, radio etc. o Hard defence options o Vertical evacuation options o Risk assessment

**Comment by pgiraud** [comment]
@stufraser1 It looks like github changed the formatting as well.
Can you please send me an example of the text within a word document by mail?

**Comment by stufraser1** [comment]
@pgiraud 
Please see the 4th white box down for the corresponding word file.

[2_TSUNAMI_LOCAL REGULATIONS.docx](https://github.com/GFDRR/thinkhazard/files/214642/2_TSUNAMI_LOCAL.REGULATIONS.docx)
