### ISSUE TITLE
Admin interface: internal error

### ISSUE THREAD

**Issue by NicolasT-brgm** [GFDRR/thinkhazard#549]
Quand on change l'ordre des recommandtions dans la page HAZARD category, le chzngeùent n'est aps pris en compte si on clique sur save change, ou alors le message d'erreur internal error est retourné.

**Comment by arnaud-morvan** [comment]
I have not managed to reproduce the error.

**Comment by pgiraud** [comment]
This is most probably due to wrong apache configuration. See #605. Closing.
