### ISSUE TITLE
Admin interface : usability for technical recommendations

### ISSUE THREAD

**Issue by NicolasT-brgm** [GFDRR/thinkhazard#550]
technical recommendations are not ordered.
So it is difficult to find for example a recommendations that was just created.

**Comment by fjacon** [comment]
it would be nice to have filters on hazard type and hazard level ?

**Comment by stufraser1** [comment]
Yes, agreed.

**Comment by tonio** [comment]
Ordering & text filtering deployed in production.

**Comment by stufraser1** [comment]
Thats helpful, thank you. Happy with this. closing
