### ISSUE TITLE
Add images to About page

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#566]
Logos and coverage map to be added to about page - please see attached zips, and associated text:

The following organizations have contributed data and / or expert input to the development of this tool:
[Logo.zip](https://github.com/GFDRR/thinkhazard/files/199780/Logo.zip)

ThinkHazard! holds local data for the countries displayed in this map. Global data is available for river flood, earthquake, cyclone, water scarcity, and landslide.
[Data_Holdings-01.zip](https://github.com/GFDRR/thinkhazard/files/199779/Data_Holdings-01.zip)

**Comment by pgiraud** [comment]
Hi @stufraser1 
The logos look weird.
First, these are actually jpeg/png images embedded in SVG. If we don't find real vector files, let's use original files instead.
Second, only the GNS one look correct. Others look like a mix of several images or are cropped (SSBN).

I tried to google for SVG files for the given organizations. Search looks like "keyword filetype:svg".
My first attempt gave good results. It was worth trying.
https://upload.wikimedia.org/wikipedia/de/2/2a/Institute_of_Geological_and_Nuclear_Sciences_Logo.svg
But I don't feel lucky for the other logos.
Can you help me? Or at least provide the png/jpeg original files?

**Comment by pgiraud** [comment]
University of Canterbury found.
https://upload.wikimedia.org/wikipedia/de/f/f9/University_of_Canterbury_Logo.svg

**Comment by stufraser1** [comment]
Hi
I remade the .svg for SSBN using svg convertor and manual color in InkScape. Hopefully this one works better. The others are attached as the original formats provided
[contributors.zip](https://github.com/GFDRR/thinkhazard/files/206579/contributors.zip)

**Comment by stufraser1** [comment]
GNS in svg format 
[Institute_of_Geological_and_Nuclear_Sciences_Logo.zip](https://github.com/GFDRR/thinkhazard/files/206594/Institute_of_Geological_and_Nuclear_Sciences_Logo.zip)

**Comment by stufraser1** [comment]
@pgiraud 
We have two more logos to add. Sorry!
[Logo-selected.zip](https://github.com/GFDRR/thinkhazard/files/208775/Logo-selected.zip)
