### ISSUE TITLE
Add a "zoom out to upper-level area" button

### ISSUE THREAD

**Issue by elemoine** [GFDRR/thinkhazard#59]
This button wouldn't be displayed when the current administrative division is an admin 0 (country).

![thor-front-office-report-details-v3](https://cloud.githubusercontent.com/assets/76594/7510235/361afc60-f49a-11e4-8aae-b96aa3b6aceb.png)

**Comment by pgiraud** [comment]
It would be probably be even better if we put the name of the upper-level area.
ie. "Zoom out to Morocco"

**Comment by elemoine** [comment]
+1

**Comment by pgiraud** [comment]
Fixed via #78.
