### ISSUE TITLE
Flood: Layer source of 'owner'

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#602]
Data source, displayed beneath the map in UI, display the data owner.
For river flood, this is incorrectly displaying the owner of the mask layer (GFDRR), when it should display the data source as the owner of the return period layers (alfieri-et-al)

example: http://thinkhazard.org/report/85-france/FL

**Comment by pgiraud** [comment]
As far as I understand, we should never get the owner from the mask layer since it may be falsy.
