### ISSUE TITLE
Add link to go to upper-level area

### ISSUE THREAD

**Issue by elemoine** [GFDRR/thinkhazard#61]
https://github.com/GFDRR/thinkhazard/issues/59 suggests adding to the map a button to "zoom out to the upper-level area". This issue suggests also adding a link with the same effect.

![thor-front-office-report-overview-v3](https://cloud.githubusercontent.com/assets/76594/7510362/6df74ade-f49b-11e4-9f25-843a363b50e7.png)

**Comment by pgiraud** [comment]
Fixed with https://github.com/GFDRR/thinkhazard/pull/78.
