### ISSUE TITLE
Searching "administrative divisions" has gotten too slow

### ISSUE THREAD

**Issue by elemoine** [GFDRR/thinkhazard#62]
We need to find a way to optimize the search. It's gotten too slow since the switch to the new database model (where all the admin divisions are in the same table).

**Comment by stufraser1** [comment]
Related to this: 
When users type a location name into the search bar and try to press enter, it doesn't work immediately;  they must wait for the dropdown list to appear before they can press enter and have it work successfully.
If the search of admin divisions cannot be sped up, can we allow users to press enter without having to wait for the dropdown list to appear?

**Comment by pgiraud** [comment]
This issue does not seems to be relevant anymore. Please reopen if you don't agree.
