### ISSUE TITLE
Splitting CY data to regions

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#620]
@NicolasT-brgm said in another issue:
Yes seems work now for CF. But I am afraid the same issue is true for CY: CY data are local (mostly tropical regions) if I understand well. Is there data for mainland France (VL as displayed) or should France be No data?. Nicolas
My response: GAR15 does not contain data for France - this should be no data in the tool. Andy and I can solve this.

@pgiraud Can you confirm, if raster values are NoData, then they will be considered in ThinkHazard! as no data? If they are zero value, they will be considered according to thresholds?

I ask because the cyclone data is more continuous than global CF data - it is harder to split to regions. An easier adjustment for us is to retain a single global dataset, but make all zero values NoData.

**Comment by pgiraud** [comment]
Yes we confirm that NoData pixels in the raster file are not taken into account whereas a zero value pixels are considered.
So modifying the raster file and change zero to NoData should do the job.
