### ISSUE TITLE
SHARE data not showing for FR

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#621]
@NicolasT-brgm 
SHARE data had an incorrect data quality rating (the ratings were entered in the boxes the wrong way round, so the high quality calculation rating of 7, was capped at 2).
Therefore, France shows global data. 

@pgiraud Will this be updated in the next harvest, considering that nothing else on the layer has changed (i.e., will this change be ignored by the process)?

**Comment by pgiraud** [comment]
@stufraser1 metadata changes will be taken into account. The processing will not be done again for the given hazard set but the decision tree will take the new quality rating values into account.

**Comment by stufraser1** [comment]
Viewed on the preview interface, SHARE is being used for France
