### ISSUE TITLE
download of specific hazardset doesn't seem to do anything

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#636]
Nothing seems to be downloaded when I use the following command:
```
.build/venv/bin/download --hazardset_id FL-GLOBAL_GAR15
```

**Comment by arnaud-morvan** [comment]
In my development database this hazardset is named FL-GLOBAL**-**GAR15 with two minus sign.

**Comment by pgiraud** [comment]
Crap. My bad.
