### ISSUE TITLE
Data source for GLOFRIS layer in preview = None

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#641]
e.g., http://thinkhazard.org/admin/preview/report/85-france/FL

The data source for GLOFRIS = None, where it should read GLOFRIS. (I updated this in Geonode, as Deltares are not the only owner). I though that the tool reads data source directly from the Geonode layers, so this should work OK? 

I expect this will update when the data are published?

**Comment by pgiraud** [comment]
If I look at the layers metadata from geonode the value for owner__organization for the 3 GLOFRIS  layers is `null`.
http://45.55.174.20/api/layers/

You may have mixed `owner__username` and `owner__organization`.

**Comment by stufraser1** [comment]
OK, I'll try to correct this now... sorry.

**Comment by stufraser1** [comment]
I've updated Geonode users with the user_organization field.

**Comment by pgiraud** [comment]
Works now. Closing.
