### ISSUE TITLE
MMI not supported in v1

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#648]
It's important that this dataset EQ-RS-IF is included by launch. 
@NicolasT-brgm please can you suggest threshold values commensurate with the current PGA thresholds?

**Comment by NicolasT-brgm** [comment]
I am sorry, but it is not possible now. This is not trivial, and I am out of the office until May 9
I just have a very short time window end of the afternoon to send the report and the tool.

MMI is not correlated to PGA in a simple maner as far as I know. it refers to intensity not acceleration, and is not EMS 98 scale. note that intensity(EMS98)/PGA formula are approximate. 
using MMI data requires real work and modification of the report methodology.

**Comment by stufraser1** [comment]
Impact Forecasting have tested relationships between MMI and PGA during their model development processes. They will recommend, for each country they are providing data, the most appropriate relationship to convert MMI to PGA. They have no time to convert the rasters, so I will convert in GIS the MMI rasters they have sent me, into PGA. The PGA rasters will be uploaded to Geonode, to be used in the tool.
