### ISSUE TITLE
UI component out of place on Safari

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#649]
It's just been flagged to us, that viewing the UI on Safari produces one component out of place on the overview page: see the grey 'hazard level; bar, which is vertical on other browsers, is shown horizontally across the river flood entry
![screen shot 2016-05-04 at 11 25 15 am](https://cloud.githubusercontent.com/assets/12515042/15019246/315de50e-1215-11e6-9be8-6902b054692b.png)

**Comment by pgiraud** [comment]
I can confirm that this happens on Safari < 8.
