### ISSUE TITLE
Map conflict (clicking)

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#654]
Users are unable to click on admin units that lie beneath the 'zoom out to' box.
This means that for some areas, users cannot navigate to particular units. See http://thinkhazard.org/report/3227-united-states-of-america-illinois for an example - the most northerly admin 2 units are inaccesible

**Comment by pgiraud** [comment]
We have two options.
 - change the layout and move the buttons outside the map.
![screenshot from 2016-07-18 13 23 20](https://cloud.githubusercontent.com/assets/319774/16913707/beb14f74-4cec-11e6-954f-8c06ed3659e5.png)
 - Make it so the division isn't too close to the top (and bottom) of the map container. Will apply only for division that are higher than wide.
![screenshot from 2016-07-18 13 18 43](https://cloud.githubusercontent.com/assets/319774/16913720/e10fb678-4cec-11e6-89d3-5948829fca4d.png)

What do you think?

ping @stufraser1

**Comment by stufraser1** [comment]
Thanks. I think the first option is more suitable. We already have a problem that some island states are not clearly visible, so increasing the gap between map border and admin unit, would only increase that problem.

**Comment by pgiraud** [comment]
Fixed with #660
