### ISSUE TITLE
Hits on each page

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#658]
We would like to retrieve a list of hits on each page, to track which countries and perils are being viewed most. This has not been activiated in the Google Analytics, so I am hoping it is possible to retrieve this information via Camptocamp analytics?

I see the user flow in Analytics, but I'm not sure we can summarise that usefully:
https://analytics.google.com/analytics/web/#report/visitors-flow/a75301865w113660687p118778909/%3F_u.date00%3D20160509%26_u.date01%3D20160714%26_r.threshold%3D0%26_r.hlEdgeStartNode%3D1-1-2009270859%26_r.hlEdgeEndNode%3D14-0-510118739%26_r.steps%3D13/

**Comment by pgiraud** [comment]
Hi @stufraser1
You can get the information with Analytics.
https://analytics.google.com/analytics/web/#report/content-pages/a75301865w113660687p118778909/%3F_u.date00%3D20160401%26_u.date01%3D20160717%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.rowCount%3D5000%26explorer-graphOptions.selected%3Danalytics.nthMonth/

You should be able to export this and analyse it in a calc software.
Does it help?

**Comment by stufraser1** [comment]
Thanks! I must have missed this page altogether. this will work, with some manipulation of page tag in excel

**Comment by stufraser1** [comment]
So, I think I need a a lookup list of the admin 3 code, and corresponding admin0 name. 
As shown on thinkhazard.org/admin/admindiv_hazardsets/FL
Can you provide that, or can I retrieve it from somewhere on github?
