### ISSUE TITLE
A3. New interactive map (implement in version 2)

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#661]
Andy has completed an interactive map using leaflet, to show our coverage of data held in Geonode and used in ThinkHazard! by hazard and country. Please replace the existing static map in the About page, with this one. Files attached to this issue. To implement as part of version 2 software improvements. 

GFDRR will need to update this map periodically once it is implemented. I assume this can be done easily via the geojson file if the code is hosted on GitHub?

[TH-InteractiveDataMap-Version2.zip](https://github.com/GFDRR/thinkhazard/files/486769/TH-InteractiveDataMap-Version2.zip)

**Comment by stufraser1** [comment]
@pgiraud 
The value of this map is increasing among our users, based on feedback we've received recently. We would therefore prefer to have this located not in the About page, but on its own page, ideally with a link next to About/FAQ/Feedback in the top toolbar. Do you think this would be possible instead of embedding in About page?
The static map should still be removed

**Comment by pgiraud** [comment]
This should be possible.
@stufraser1 please tell us what would be the text for the link as well as what the new page should contain (apart from the map).

**Comment by stufraser1** [comment]
The link text should read 'Data map'

Above the amp, please include the text: 
'ThinkHazard! classifies hazard using global, regional and national data. Coverage of each hazard varies around the world. Click on a country to see the data available for the selected hazard.' 

And below the map (can be smaller text):
'The boundaries, colors, denominations, and other information shown on any map in this work do not imply any judgment on the part of The World Bank concerning the legal status of any territory or the endorsement or acceptance of such boundaries. Source of Administrative boundaries: The Global Administrative Unit Layers (GAUL) dataset, implemented by FAO within the CountrySTAT and Agricultural Market Information System (AMIS) projects.'

**Comment by pgiraud** [comment]
Here's the demo of what I did so far: http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/data_map/

It looks like I made the wrong assumption by thinking that the map was supposed to show the data source used to compute the hazard level for each country for a given hazard type.
It only displays the result after the decision tree has done its job. Just like we do in the report page or in the hazardsets / admindiv page on the admin interface.

Is the map supposed to show all the datasets that were harvested / downloaded from GeoNode before the different rating have been applied and the computation has been done?

**Comment by stufraser1** [comment]
The map is to show coverage of data available to us, rather than what is used to compute hazard. 

The map is supposed to show, in its shaded colour, the highest level of data that we use for that country. So the default is that all countries show the colour for 'global' but for countries covered by SHARE data in Europe, it would show regional. For a countries that we have a national model, it would show as national rather than regional.
The pop-up box is designed to show which datasets exist on the GeoNode for ThinkHazard! (i.e., multiple may be available at each level, but cannot all be used to generate the hazard level)

Related to the labelling of datasets in the interactive map:
We really need it to show more than 'global' and 'local'. You said these would be used because that is the only distinction associated with the data set (this is based on analysis of the domain extent, and is also used for decision tree).

We have in the metadata for each layer, a metadata field 'Regions'. However, his doesnt appear when you look at e.g., http://45.55.174.20/api/layers/?hazard_type=earthquake
![image](https://cloud.githubusercontent.com/assets/12515042/22371479/3ca00bd4-e48f-11e6-813a-e44d43dca40d.png)

In this field we select region(s) or country(ies) to assign the layer to. There is also a 'global' option.

Could there be a rule such as : 
IF 1 option is selected THEN
IF regionField = 'global' THEN [global] ELSE
IF regionField = 1st level or 2nd level option THEN [Regional] ELSE 
IF regionField = 3rd level option THEN [Regional] ELSE
IF > 1 option is selected THEN [Regional] (because this indicates that the dataset covers more than country, region, or subregion.

(where [...] signifies the label applied on the interactive map)
(Example levels 1st level: Africa, 2nd level: Southern Africa; 3rd level: Botswana)

My hope is that this field provides an easy way to provide the required labelling on that interactive map - if you can access that field in GeoNode

**Comment by stufraser1** [comment]
The current version looks good. My comment above is reinforced by looking at the EQ map - a lot appears as local, but this is not really easy for users to understand - so we need that regional / national distinction.

It is also very slow.

**Comment by stufraser1** [comment]
New version of data map, to replace the current version please:
[TH-InteractiveDataMap-Version4.zip](https://github.com/GFDRR/thinkhazard/files/1007941/TH-InteractiveDataMap-Version4.zip)

**Comment by fjacon** [comment]
@tonio can you update the map ?

**Comment by tonio** [comment]
GeoJSON file updated on integration.
