### ISSUE TITLE
Adding logos to About page

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#667]
World Bank logo should be added alongside camptocamp, brgm deltares:
![wbg_horizontal-black-high](https://cloud.githubusercontent.com/assets/12515042/19807319/6ed55c54-9d17-11e6-9dd4-c0648e484620.png)

The following companies need to be added to contributor logos on the About page (beneath GNS, UNISDR, UNDP, etc):
Impact Forecasting
Utrecht
Global Earthquake Model 
Geoscience Australia
Karlsruhe Institute of Technology
University of East Anglia
PCRAFI

![if_logo](https://cloud.githubusercontent.com/assets/12515042/19770603/c907e8b0-9c57-11e6-8121-65204a22622c.png)
![universiteit-utrecht](https://cloud.githubusercontent.com/assets/12515042/19732484/c68589a4-9b98-11e6-8ed2-a6aee4c22b60.png)
![ga](https://cloud.githubusercontent.com/assets/12515042/19728902/1345000a-9b8d-11e6-8198-860161d55397.png)
![gem-logo-red-cmyk-300dpi](https://cloud.githubusercontent.com/assets/12515042/19802424/88efa4bc-9cfb-11e6-8955-883054419648.png)
![pcrafi](https://cloud.githubusercontent.com/assets/12515042/19728904/134cd9a6-9b8d-11e6-885f-c16d26d9cc36.png)
![uea](https://cloud.githubusercontent.com/assets/12515042/19728906/134dbab0-9b8d-11e6-84eb-bff345e5d776.png)
[Logo_KIT.zip](https://github.com/GFDRR/thinkhazard/files/553404/Logo_KIT.zip)

**Comment by pgiraud** [comment]
@stufraser1 can you provide me with the link I should add for each contributor logo?

**Comment by stufraser1** [comment]
Impact Forecasting - http://www.aon.com/impactforecasting/impact-forecasting.jsp
Utrecht http://www.uu.nl/en/organisation/faculty-of-geosciences
Global Earthquake Model - http://www.globalquakemodel.org/
Geoscience Australia - http://www.ga.gov.au/
Karlsruhe Institute of Technology - https://www.gpi.kit.edu/english/GPIatKIT.php
University of East Anglia - https://www.uea.ac.uk/
PCRAFI - pcrafi.sopac.org/
