### ISSUE TITLE
Updating FAQs

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#668]
We have a list of updated FAQs, attached.
I can update the text file in its current format, but we would like to explore whether it is possible to include functionality to have question presented as a drop-down -- i.e. the answer is hidden until user clicks on a question text, at which point the answer appears

[ThinkHazard FAQs_v3.docx](https://github.com/GFDRR/thinkhazard/files/553723/ThinkHazard.FAQs_v3.docx)

**Comment by stufraser1** [comment]
Please note that further changes have been made; GFDRR to supply latest version in December

**Comment by stufraser1** [comment]
Attached, version of FAQs to go on TH! v2.
This contains hyperlinks, request to include an image, and request to include dropdowns to show answers (with default view to list question only).

[ThinkHazard FAQs_v7.docx](https://github.com/GFDRR/thinkhazard/files/642288/ThinkHazard.FAQs_v7.docx)

**Comment by pgiraud** [comment]
@stufraser1 If I'm not wrong you would like to include images in the FAQ answers? Not only text with links, right?

**Comment by stufraser1** [comment]
One image at this stage, to help with users' understanding. If this poses a problem, we may be able to find another way, without the image.

**Comment by pgiraud** [comment]
@stufraser1 The FAQ for v2 has been updated. With the collapsible blocks.
You can see it here:
http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/v2/

Any feedback is welcomed.
I'm waiting for an image to put in the "How does TH! work?" section.

**Comment by stufraser1** [comment]
@pgiraud Thank you

This looks pretty good, thank you. I think the text could be made smaller, it seems quite large at the moment. Can you make the section titles closer to the current font size of the questions, and reduce the font size of question titles by 1, or bring to equal the font size of question response text (the bold and blue colour may differentiate the title enough)

Regarding the image, Hopefully this is sufficiently high resolution for the size required:
![about_image](https://cloud.githubusercontent.com/assets/12515042/21645816/83b9b242-d28b-11e6-8933-a7da378cbcf6.png)

**Comment by pgiraud** [comment]
You are right, I changed the font sizes and it looks much better.
https://github.com/GFDRR/thinkhazard/pull/708

I also integrated your image but I see 2 problems:
 - it doesn't use the new colors,
 - it's blurry even in its original size.

**Comment by stufraser1** [comment]
OK, I'd like to try to update this with a new version of Bolivia map, rather than the countries available in the v2 demo, as it was chosen for the nice map view of the coutnry and variaiton in hazard, which you dont get with, say, Indonesia (which is a smaller in the map window, so less useful in an explanation piece. Please let me know when Bolivia is available in v2, and I'll pull out the new map image. Note that in my view on firefox, I just see a black box with '600*400' written in it.

The text looks better, thank you.

**Comment by pgiraud** [comment]
@stufraser1 Bolivia is already available in the v2 demo.
http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/v2/report/33-bolivia/EQ

**Comment by pgiraud** [comment]
@stufraser1 Instead of creating a big image with Boliva, legend, Oruro and header I decided to creating one image for each and assemble them into the faq layout.
Here's how it looks:
![screenshot from 2017-01-10 17 04 56](https://cloud.githubusercontent.com/assets/319774/21813553/f7b7d3fc-d756-11e6-85b7-7c73f7dd537c.png)

It's in my opinion easier to manage and maintain.

If you agree, I'll merge this pull request.

**Comment by stufraser1** [comment]
@pgiraud Thank you for this solution: I think this would work very well. One thing I would really like to have above or below each map is the label of the areas shaded (i.e. Oruro on left, Bolivia on right). This is important for viewers to relate what the area on the left actually is.

**Comment by pgiraud** [comment]
http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/v2/ updated with the latest FAQ layout and images.
Closing the current issue for now. Please reopen if you have any additional comments.
