### ISSUE TITLE
Add widget to share thinkhazard

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#673]
Can we add a widget to share the hompage and some text, on twitter / facebook ?

**Comment by stufraser1** [comment]
Can this be actioned fairly easily?
One questions is where to place on the page. Thoughts?

**Comment by tonio** [comment]
Proposition mockup:

_Home page (footer unfocused)_

![screenshot from 2017-09-15 14-04-59](https://user-images.githubusercontent.com/21686/30481584-bf7f468c-9a1f-11e7-866e-e9490b7bf037.png)

_Home page (footer focused)_

![screenshot from 2017-09-15 14-05-10](https://user-images.githubusercontent.com/21686/30481585-bf85aac2-9a1f-11e7-8532-ca5729cbb6a5.png)

_Report page (links unfocused)_

![screenshot from 2017-09-15 14-12-17](https://user-images.githubusercontent.com/21686/30481644-180698fa-9a20-11e7-9aa6-862db435bc22.png)

_Report page (links focused)_

![screenshot from 2017-09-15 14-12-26](https://user-images.githubusercontent.com/21686/30481643-1805e036-9a20-11e7-864f-eb7a5782b1f9.png)

**Comment by fjacon** [comment]
@stufraser1 waiting for your feedback here, thanks !

**Comment by stufraser1** [comment]
I think we should use only the twitter/FB icons, not the text too. Will save space and I think everyone knows what they mean. Other issue is branding and the icons appear too close to gfdrr logo.
On the home page can we put in header to the right of the language toggle? And on all hazard overview/information pages can it go to the right of the feedback request box at the bottom of screen? Ideally it would be in the header on these pages too, but I recognise the lack of space there.

**Comment by tonio** [comment]
The problem with icon only is that you don't know if you're going on TH!'s facebook(or twitter) page or if it is a sharing link…
I'll try with your location proposition.

**Comment by stufraser1** [comment]
True - can you use something short, like 'Share: <icon><icon>'?

**Comment by tonio** [comment]
I just deploy a branch on integration for testing.

**Comment by stufraser1** [comment]
Looks good, seems to work well. Happy with this.
