### ISSUE TITLE
Move feedback link to top

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#674]
As the pages are getting longer, it seems we should move the feedback button into the header.

1. Remove the text "We welcome any suggestions for improvements to the tool, including suggestions of data, recommendations, or resources to include. If you have any, please provide feedback."

2. Include the same link to form, as text "User feedback" in header, immediately to the left of 'About' and 'FAQ'

3. INclude on home page in addition to all location specific pages

**Comment by pgiraud** [comment]
Here's how it would look.
![screenshot from 2016-12-07 15 52 31](https://cloud.githubusercontent.com/assets/319774/20972458/2e9a3540-bc95-11e6-8f12-ac50cfe92e56.png)

Is it visible enough?
There may be other solutions including putting a button at the edge of the browser window.

**Comment by stufraser1** [comment]
GFDRR think this suggestion is visible enough. 
Please retain the feedback button as it is, at the bottom of the page too.
