### ISSUE TITLE
A4 - About page: Remove Map disclaimer

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#675]
remove map dislaimer in About (this will be place instead in disclaimer at home page)
'The World Bank does not guarantee the accuracy of the data included in this work. The boundaries, colors, denominations, and other information shown on any map in this work do not imply any judgment on the part of The World Bank concerning the legal status of any territory or the endorsement or acceptance of such boundaries.

Source of Administrative boundaries: The Global Administrative Unit Layers (GAUL) dataset, implemented by FAO within the CountrySTAT and Agricultural Market Information System (AMIS) projects.
'

**Comment by pgiraud** [comment]
Fixed via #702.
