### ISSUE TITLE
DIsplay of disputed areas

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#678]
In the map window, users need to be able to better identify disputed areas and distinguish disputed borders from agreed borders.

Use case: Jammu & Kashmir, northern border of India. Indian users have stated it is missing from map when they search 'India'. WB officially recognises it as disputed, so we shouldn't attribute it to India. 
We should identify it as disputed and show it when India is shown though.
This required two things:
1. To show a different border style based on GAUL attribute 'DISP_AREA' (options: 'YES' or 'NO') - typically a dashed line for disputed areas (see image). Applies to borders shown at ADM_0, 1, 2.
2. To show admin units not included in the searched country, limited to those falling within the view-box. This would indicate to people searching India, that J&K is on the map, but distinguished differently. THey could then click on J&K on the window to see its hazard levels. At the moment they can't see J&K unless it is specifically searched. Actioning this would give us justification for not attributing it to India.
Showing admin units in neighbouring countries also benefits seeing cross-border hazard levels. 

![image](https://cloud.githubusercontent.com/assets/12515042/20630171/48887588-b327-11e6-9dce-1d3e91a3526f.png)

**Comment by fjacon** [comment]
This issue is not simple at all. We definitely need to think it over carefully as it has important impacts on the application. Is this a priority ?

**Comment by stufraser1** [comment]
Yes this is important, as we have had issues with users suggesting we're not representing these areas correctly. Please could you summarise the steps required to do this, and most importantly the implications on the application so I can understand this more?

**Comment by pgiraud** [comment]
As discussed during the monthly meeting:
 1. A mapbox tileset provided and maintained by WB is to be used. It is supposed to show the disputed areas.
 2. Camptocamp to propose a way to add interaction on the map for neighbouring divisions. Showing levels for the neighbouring divisions doesn't seem to be a good idea though because it may tend to a messy information for the end-user.

**Comment by pgiraud** [comment]
I just created an instance on the demo server to show what the WB tileset look like. We can see the disputed areas.
http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/bglayer/report/115-india

**Comment by stufraser1** [comment]
I think this works well to show the boundaries. @vdeparday - your thoughts?

**Comment by stufraser1** [comment]
One thing this does not solve, is that when someone searches 'India' it does not include Jammu and Kashmir (disputed) within the country, so complaints it doesn't show the whole country when searching 'India' have not been addressed.
It may not be possible to achieve both inclusion of Jammu and Kashmir in India *and* showing is as disputed territory 
I believe that if we change the shapefile so that J&K polygon was merged with India, and all J&K ADM1/ADM2 codes to be children of India, then we would not see the disputed boundary on the map, @pgiraud could you confirm if you expect this too?

**Comment by pgiraud** [comment]
@stuart Here's the demo enhanced with interaction for the neighbouring divisions. This improves the user experience a lot in my opinion.
http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/bglayer/report/1489-india-delhi

**Comment by stufraser1** [comment]
Hi. Yes that's nice. I'm on a tablet and it only works at adm1 level not adm2. I think users would expect it to work the same way on 2 if they've done it on level 1. Had you planned to do it on both levels?

**Comment by pgiraud** [comment]
It is fixed.
I also made it so the hazard type is kept from one page to the other when clicking on neighbouring division.
If this works for you, I'll create a pull request so that it can be integrated in v2.

**Comment by stufraser1** [comment]
This looks great, thank you, please integrate to v2
