### ISSUE TITLE
A8 - Add contacts listing to recommendations

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#681]
Contact listing to contain Name, Phone, URL, email, for >1 contact for each combination of country and hazard. Contacts may be valid for >1 hazard and/or country, but may will be relevant to a single country and hazard combination (unlike climate recommendations, which is what this most closely relates to).

To be added in recommendations panel on UI? Or under map? 
It should be included with capability to manage contents in admin UI

Final listing available mid-January. Draft listing (for early view of format): 
[hazardCountryList_Organizations_Nov16.txt](https://github.com/GFDRR/thinkhazard/files/619131/hazardCountryList_Organizations_Nov16.txt)

**Comment by pgiraud** [comment]
Here's what I propose for the UI.

![screenshot from 2016-11-30 17 43 31](https://cloud.githubusercontent.com/assets/319774/20761858/ad15b0b4-b724-11e6-9e0a-753df234c227.png)
![screenshot from 2016-11-30 17 44 08](https://cloud.githubusercontent.com/assets/319774/20761865/b0f41efa-b724-11e6-981f-6559aa0aa6a9.png)

**Comment by stufraser1** [comment]
Interesting and clean solution, please let me discuss with GFDRR team before confirming to you.

**Comment by pgiraud** [comment]
Instead of opening a modal window, I think it's better to display the detailed information within a collapsible/expandable element.

![screenshot from 2016-12-07 11 39 07](https://cloud.githubusercontent.com/assets/319774/20964434/d1dbd624-bc71-11e6-9684-6dd37dd6950b.png)
![screenshot from 2016-12-07 11 40 04](https://cloud.githubusercontent.com/assets/319774/20964460/e8c65620-bc71-11e6-9294-f9152ad0297d.png)

**Comment by stufraser1** [comment]
GFDRR preference is to have the contacts listed as you suggest in a box titled Contacts. The user should click on the contact name to display the contact details, as per your second suggestion.
Please can you include the contact details for each contact on the printable PDF report

**Comment by pgiraud** [comment]
For the format of the file, it will be important to provide the administrative division code (for example 249 for Turkey) in the final listing.
See https://github.com/GFDRR/thinkhazard/blob/master/data/climate_change_recommendations.csv

**Comment by stufraser1** [comment]
I have included the ADM0_CODE in this attached table, which is an updated version of the earlier table.
[hazardCountryList_Organizations_20161207.zip](https://github.com/GFDRR/thinkhazard/files/654497/hazardCountryList_Organizations_20161207.zip)

It contains all World Bank countries (so far, between one and three contacts only given for selected priority countries). It may not be possible to complete contacts for non-priority countries prior to version 2 release, so we need to have a function to let users know there are no contact details, and to please provide some if they know of any, via the feedback button. 
How do you think it is best to do this?

**Comment by pgiraud** [comment]
@stufraser1 Is it possible for you to provide the contacts listing using the mnemonic for the hazard types?
Complete list of mnemonics can be found [here](https://github.com/pgiraud/thinkhazard/blob/pgiraud_new_icons/thinkhazard/scripts/initializedb.py#L121-L132). It includes the new hazard types.

**Comment by stufraser1** [comment]
revised listing with hazard codes (field = HAZID, in column 5), attached
[hazardCountryList_Organizations_20161229 - uploaded to github.zip](https://github.com/GFDRR/thinkhazard/files/684752/hazardCountryList_Organizations_20161229.-.uploaded.to.github.zip)

**Comment by pgiraud** [comment]
@stufraser1 the ADM0_CODE is missing in your latest attached file.

**Comment by stufraser1** [comment]
attaching a cleaned and double-checked version.
[hazardCountryList_Organizations_20170106.zip](https://github.com/GFDRR/thinkhazard/files/689924/hazardCountryList_Organizations_20170106.zip)

**Comment by pgiraud** [comment]
I just finished and merged the code for importing contacts and displaying them in the interface.
The result can be seen here:
http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/v2/report/116-indonesia/FL

**Comment by stufraser1** [comment]
Contacts listing is not seen on int server, and there are none listed in http://int.thinkhazard.org/admin/contacts

Dev server does not show this, either.

We provided a list in this issue - please upload these for v2 launch

**Comment by tonio** [comment]
I reimported contacts on integration & fix a bug when editing them.

**Comment by fjacon** [comment]
@tonio the contacts appear in the admin tool but not on the front end. Can you check ?

**Comment by pgiraud** [comment]
@fjacon are you sure you checked the (admin) preview? Contacts may not appear on the public interface until the data is published.
http://int.thinkhazard.org/admin/preview/en/report/116-indonesia/FL

Sorry couldn't resist.  ;-)

**Comment by fjacon** [comment]
@pgiraud thanks !!

**Comment by fjacon** [comment]
@stufraser1 is OK for you now ?
