### ISSUE TITLE
A4. Add disclaimer to home page of ThinkHazard!

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#682]
a. To be included as a pop-up that must be read and/or accepted to continue to enter a search location. 
b. For example, the opening to: http://floods.wri.org/ (though this does not include a disclaimer)
c. GFDRR to provide text of disclaimer

**Comment by pgiraud** [comment]
@stufraser1

Should the pop-up be displayed each time the user opens the home page? Or should we remember user's decision and prevent the pop-up from showing again?

Should the pop-up be displayed on the home page only? What if the user lands directly on a report page?

**Comment by stufraser1** [comment]
Users should see the disclaimer if landing directly on a report page.

Users should see the disclaimer every time they visit the site, as a reminder of the issues, I think. But do you have advice on whether that is too much, and provides a dusruption to easy use? We need to have a balance on this issue

**Comment by stufraser1** [comment]
Part of the disclaimer - the paragraph stating licences - should be added to about page please

**Comment by pgiraud** [comment]
What we can do is check the referrer (ie. where the user comes from). If it's null or different from the TH! website then we can display the disclaimer.

**Comment by pgiraud** [comment]
@stufraser1 I'm not sure what text to use for the disclaimer in the modal.

> Part of the disclaimer - the paragraph stating licences - should be added to about page please

What paragraph stating licences are you talking about?

In #675 you refer to some text to be put in the disclaimer window.

Also, there is a more detailed disclaimer in the PDF output.
https://github.com/GFDRR/thinkhazard/blob/master/thinkhazard/templates/pdf_about.jinja2#L19-L33

This is not clear to me.

**Comment by stufraser1** [comment]
Sorry for not being more clear.

The full disclaimer attached should be presented in the modal when landing on TH home page (#702)  
[TH_Disclaimer_text_v3.docx](https://github.com/GFDRR/thinkhazard/files/684814/TH_Disclaimer_text_v3.docx)

The About page should contain minimal disclaimer information - It should contain only the licence information (section in attached entitled 'Licence', and if possible, a link to the full disclaimer (link text to read 'Full disclaimer').

Regarding the pdf report:
Please present the section from the attached, entitled 'Disclaimer' followed by the section 'Licence'

**Comment by stufraser1** [comment]
Feedback on disclaimer from GFDRR team - 
1. Can we remove the 'x' in top right corner, therefore forcing users to click 'agree'
2. Can we shrink the text so the box fits on a smaller screen without scrolling? This clearly depends on the size of screen, so there will always be a screen that requires scrolling, so if you think there are detrimental impacts to reducing text size from its current size, then please highlight this and we'll retain the current size.

**Comment by pgiraud** [comment]
1. It's a good idea. I'll provide a pull request in which I also prevent users from dismissing the modal but typing on the ESC key or clicking on the backdrop (mask around the modal).

2. I can't anything satisfactory by shrinking the text or widening the modal. Even on large screens the modal tends to be need some scroll in most cases.

**Comment by stufraser1** [comment]
To reduce the length of the disclaimer modal window, which requires users to scroll down to 'agree', please could we shorten the text displayed by default under section 'Disclaimer', and have a 'more...' button at the start of the second paragraph 'Information in this screening tool...', which when clicked will reveal the rest of the disclaimer? The 'I agree' button should appear by default on the right, in line with the 'More ...' link, so that it can be seen on the page without scrolling. Thank you

**Comment by tonio** [comment]
PR #744 has been merged and deployed to http://int.thinkhazard.org/

**Comment by stufraser1** [comment]
This is an improvement, thank you. I think we can close this.
