### ISSUE TITLE
A1 - Add extreme heat hazard type

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#686]

**Comment by stufraser1** [comment]
Extreme heat hazard data, thresholds and return periods, and rec/CC statements received. Recommendations under review. SF to enter recs/CC statements onto integration server when Pierre advises it is possible to do so.

RPs: 5, 20, and 100 yr
Unit of intensity: Wet Bulb Globe Temperature (WBGT), in degrees C. 
To be referenced in Geonode as WBGT_C 
Thresholds:
High: 32 deg_C at 5yr
Med: 28 deg_C at 20yr
Low: 25 deg_C at 100yr

EH:
    hazard_type: extreme heat
    return_periods:
      HIG: [5]
      MED: [20]
      LOW: [100]
    thresholds:
      HIG:
        WBGT_C: 32.0
      MED:
        WBGT_C: 28.0
      LOW:
        WBGT_C: 25.0

**Comment by pgiraud** [comment]
Can you confirm that there is no layer for the `extreme_heat` hazard type set in geonode yet?

**Comment by stufraser1** [comment]
Confirmed. We'll upload this week

**Comment by stufraser1** [comment]
EH data are uploaded - 
hazard set id =EH-GLOBAL-VITO
three layers 5, 20, 100 yr
units of WGBT (degree C), all included in the metadata.

Should be ready to test
