### ISSUE TITLE
A1 - Add wildfire hazard type

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#687]

**Comment by stufraser1** [comment]
GFDRR should be able to provide draft hazard data for testing, in week commencing March 13

**Comment by stufraser1** [comment]
Hazard data provided on Geonode. 
@fjacon @fvanderbiest  Can I upload the recommendations / climate change statements now? To the int server? We need to have these live to be pushed to transifex for translation.

**Comment by stufraser1** [comment]
Data for wildfire data is to be uploaded to the GeoNode this week, w/c May 1. 
Thresholds as follows: 
WF:
    hazard_type: wildfire
    return_periods:
      HIG: 2 
      MED: 10
      LOW: 30
    thresholds:      * threshold units = 'Fire Line Intensity' in FWI.
      HIG:
        FWI: 30.0
      MED:
        FWI: 20.0
      LOW:
        FWI: 15.0

**Comment by stufraser1** [comment]
WF dataset WF-GLOBAL-CSIRO is now uploaded to geonode-gfdrrlabs.
This can be harvested and tested in TH. 
@fvanderbiest are you scheduled to run a new harvest process when transfer from old geonode is complete? What is the timeframe for that?

**Comment by arnaud-morvan** [comment]
On http://int.thinkhazard.org/ we just run a new harvest of www.geonode-gfdrrlab.org.
We've completly cleared the data cache (raster files, processing outputs).
The calculation of outputs is in progress and can be followed using http://int.thinkhazard.org/admin/hazardsets.

**Comment by fjacon** [comment]
According to the admin UI we are missing a layer for level HIGH.
But I can see it on geonode :
http://www.geonode-gfdrrlab.org/layers/hazard:csiro_wf_max_fwi_rp2
@arnaud-morvan can you investigate this ?

**Comment by stufraser1** [comment]
How is progress on this? Do you think you can solve this?

**Comment by fjacon** [comment]
Arnaud is coming back next week.
Yes, no doubt it can be solved

**Comment by arnaud-morvan** [comment]
The processing parameters set in https://github.com/GFDRR/thinkhazard/commit/875df52ce1b4ab94bc7b0c796db76bd59484086a for the wildfire hazardtype was not same values as above in this issue. HIG return period was 3, so the layer with return period 2 was not matching for that hazard level. I set parameters to the values above in this issue and I relaunch the process on int server.

**Comment by arnaud-morvan** [comment]
I also note that the unit is not FWI but kW_m. If the unit is always the same, it not necessary to precise the unit. I will remove the unit intermediate keys and directly set the values on the levels for wildfire.

**Comment by arnaud-morvan** [comment]
I've just ran the harvesting on int.thinkhazard.org, WF-GLOBAL-CSIRO is now considered complete.
As I made changes on processing settings, all hazardsets have to be processed with the new parameters, this is in progess from now for some hours ...

**Comment by stufraser1** [comment]
Awaiting update of FWI in metadata options; will update unit in metadata layer. Otherwise, happy with representation of hazard classification in TH, and closing.
