### ISSUE TITLE
A1 - Add air pollution hazard type

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#688]

**Comment by stufraser1** [comment]
Please remove v2 milestone. The data is not forthcoming, and I now do not expect it to be available in time. Can we retain functionality for later inclusion (we still want to include at some stage). Icon to be removed from UI please.

**Comment by pgiraud** [comment]
See #732.

**Comment by stufraser1** [comment]
PLease confirm, full functionality added in database and UI (just awaiting data and accompanying processing thresholds to activate). If so, can close issue to be re-opened when data is received.

**Comment by fjacon** [comment]
@stufraser1 yes, everything is ready.
