### ISSUE TITLE
A5 - Map toggle view

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#689]
Toggle between color-coded admin breakdown and hazard (raw) maps.

**Comment by fjacon** [comment]
We have to discuss the design for this feature. For the moment, the best way for a user is to go directly to geonode. The link is actually available from data source below the map.

**Comment by stufraser1** [comment]
Preferred design: Tab or button to enable user to 'swap' fromt he default view of hazard levels on map (as currently used), to a map in the same place with hazard data raster shown overlaid with admin boundaries, using the same map window and extent. Legend below map to show the legend and style from Geonode.

Only one hazard map can be shown on this map. Selection of on RP where several are used in hazard classification is based on the RP usually shown by the peril experts:
EQ: [475, 500] (whichever is used for medium hazard)
RF, UF, CF: 100
CY:
VO: preprocessed layer
LS: susceptibilty map
DR: 50
TS: Pre-processed for now, but [500] hopefully in the future when we have probabilistic maps
EH: To be agreed with the consortium developing
WF: To be agreed with the consortium developing

**Comment by pgiraud** [comment]
@stufraser1
I wanted to share a prototype of what this could look like.
http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/toggle_view/report/18114-indonesia-kalimantan-selatan-kota-baru/FL

![screenshot from 2017-02-20 15 37 32](https://cloud.githubusercontent.com/assets/319774/23129328/8260dee0-f782-11e6-92d6-8ec2767ab2a4.png)
![screenshot from 2017-02-20 15 37 01](https://cloud.githubusercontent.com/assets/319774/23129331/8443c4a2-f782-11e6-95c6-3a76a8abb1bd.png)

This demo is limited to Indonesia and the River Flood hazard type. Map layer and legend are static.
Can you please give us your feedback on the usability?

Then, there's one issue we need to address. There are some rare cases where there are several possible data sources for the same division for a given hazard type.
In this case, the button "data source" could be replaced by something looking like the following.
![screenshot from 2017-02-20 15 33 57](https://cloud.githubusercontent.com/assets/319774/23129205/04a57862-f782-11e6-8152-d79bf1977200.png)

What do you think?

**Comment by stufraser1** [comment]
This looks good. A few requests:
- Toggle button to read ('show hazard level' / 'show hazard data'). Currently, it looks like a label, which describes what users are seeing on the map (which incorrectly describes hazard levels as 'data source').
- Legend requires the intensity unit and return period of hazard data used, to be shown. Can this be shown to the right of the legend, along with the data source name.
- Data source name to link directly to data layer used, in the geonode. The info popup, seems redundant with this info on main page, so can this be removed? 
- Drop-down where multiple data sources used is nice. 
- I very much like that we can navigate to neighbouring ADM unit now.

**Comment by stufraser1** [comment]
Please reduce the space taken up by hazard level legend and move data source link up towards the map. Given that the hazard data legend goes from top to bottom, and we will hopefully have the data source on the right hand side of that, please can we also place the hazard level legened in that vertical arrangement (high at top, down to very low at bottom) in one column.  If the legend and link are in the same place on both hazard level and data map it will look and operate better for user. Thanks

**Comment by tonio** [comment]
Following mockup show how we could implement a widget to chose the layer shown as a data source, by selecting the corresponding RP.

The button in the map toggles between hazard level & data source, then you could chose alternative RP to be shown in the map.

![screenshot from 2017-04-10 09-37-03](https://cloud.githubusercontent.com/assets/21686/24944256/a3a4b252-1f5a-11e7-8506-bcb375972b44.png)

**Comment by stufraser1** [comment]
Yes I like this.

**Comment by fvanderbiest** [comment]
Notes for implementation by @tonio...

You should read https://github.com/GFDRR/thinkhazard/blob/master/thinkhazard/models.py first.

The `Output` object is a result of the processing steps, and links a `HazardSet` (a group of 3 layers sharing a common id in geonode) with an `AdministrativeDivision` and a `HazardLevel` (eg: "very high earthquake risk").

For the given `AdministrativeDivision` & `HazardLevel` of the page, you should be able to identify the `HazardSet` responsible for the hazardlevel classification.

An `HazardSet` is aware of its layers (through https://github.com/GFDRR/thinkhazard/blob/master/thinkhazard/models.py#L635-L637). There's one layer per RP.

TH harvests http://www.geonode-gfdrrlab.org/api/layers/ and creates `Layer` objects in the db.

Let's take Layer Metadata with id = 1043 as an example.
It has hazard_period: "975" & hazard_set: "EQ-ALS-GEM"

The corresponding geoserver layer name can be inferred from the `detail_url` or `download_url` fields : 
 * "/layers/hazard:als07_975yr",
 * "/uploaded/layers/als07_975yr.tif",

=> layer `als07_975yr` is served by http://www.geonode-gfdrrlab.org/geoserver/hazard/ows
**This is the information you need to display the layer in the UI !**

As a result, our [Layer model](https://github.com/GFDRR/thinkhazard/blob/master/thinkhazard/models.py#L588-L649) has to be improved to access the layer name, eg:
```python
    def layername(self):
        return self.detail_url.split(':').pop()
```

**Comment by tonio** [comment]
I put a demo of the feature [here](http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/map_toggle_view/en/report/196-philippines/CF). Preselected RP is the one used to calculate level. Link is done with the corresponding geoserver layer.

**Comment by stufraser1** [comment]
This looks great. I would be happy with this, but two small adjustments to text would make it perfect, I think:
1) Toggle Button text to read 
'Show hazard class' (in place of 'Show hazard level')
'Show hazard map' or 'Show hazard layer' (in place of 'Show data source')
** TBC - need to consult with GFDRR team

2) Intensity unit for flood shows as 'm' but we need a descriptor - e.g., 'depth m' or 'windspeed km/h'. 
As this label is derived from intensity unit in layer metadata, should we update the intensity unit in metadata to read 'depth m', for example, or at the points where unit is tranlsated from metadata field (meters) to abbreviated unit (m).
This shouldn't affect all hazards, as the metadata field is more descriptice elsewhere: landslide susceptibility index, fire line intensity...

3) When users show the data source, the white space increases substantially with a large area empty beneath the legend. Can this empty space be minimised?

**Comment by fjacon** [comment]
Point 2 has been fixed a while ago.

**Comment by stufraser1** [comment]
1. not necessary at this stage. Closing
