### ISSUE TITLE
A6 - Translations

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#690]
Application should support 2 new languages:
 - French,
 - Spanish

Check list:
 - [x] Extract strings from UI,
 - [x] Extract strings from database,
 - [x] Extract strings from PDF,
 - [x] Change "name of location" to a variable in general recommendations,
 - [x] Add support for divisions name translation.
 - [x] Update database from transifex
 - [x] Add documentation for devs about how to add translatable strings in templates

**Comment by stufraser1** [comment]
@pgiraud I have made all of the amendments to version 1 technical recommendations (existing hazards) that we need to. Please can you update the source text on transifex so that I can annoucne the project on transifex on Tuesday?
For your information, on Wednesday I will meet with some translators at the World Bank to determine the potential for them to do some of the work via transifex in April, in case of gaps in the translations close to launch

**Comment by pgiraud** [comment]
@stufraser1 I'll do it this morning.

**Comment by pgiraud** [comment]
The resources in transifex have been updated.
We now have 250 (previously 324) strings to translate for the database resource.

**Comment by stufraser1** [comment]
WB Translators are presently translating with transifex. They have requested that we install Java LIve funtionality to provide them with realtime view (for immediate context) of the strings they are translating. This requires a Java snippet of code to be inserted. Steps as follow:
1. GFDRR will upgrade the Tfex subscription to enable this function on our account (as soon as translators confirm it is required, hopefully today).
2. GFDRR will copy the snippet into this issue (https://docs.transifex.com/live/installing-the-javascript-snippet#section-getting-the-snippet)
3. Camptocamp to copy snippet into code (instructions at https://docs.transifex.com/live/installing-the-javascript-snippet#section-installing-the-snippet)
This should all happen as soon as possible.

**Comment by fjacon** [comment]
@stufraser1 we wont be able to do this before Monday unfortunately.
Also, I hope it is as simple as it seems.

**Comment by stufraser1** [comment]
OK, I will try to get everything aligned by end of this week my side, so you can look at this Monday. I hope its very simple too.

**Comment by stufraser1** [comment]
It seems we won't ahve access to this Java script, so please disregard this request.

**Comment by stufraser1** [comment]
climate statements and recommendations for new hazards Urban Flood, Extreme Heat, and Wildfire. 
Please can you push these to Transifex as soon as possible

**Comment by stufraser1** [comment]
Please hold off until confirmed in meeting on 31 May - I need to add some new strings

**Comment by stufraser1** [comment]
New strings added - can be pushed to transifex now

**Comment by tonio** [comment]
I just push new strings to transifex.

**Comment by stufraser1** [comment]
Translation in progress. Pull of translated text to TH should occur end of June.

**Comment by stufraser1** [comment]
Translation completed and seems to be fully on website. Review in progress. I am waiting date for review to be finalised, but at that point, one more pull of translated text will be required

**Comment by stufraser1** [comment]
Review of translation on transifex has now been completed. Please can you pull the latest version of transifex text to ThinkHazard!
Many thanks

**Comment by tonio** [comment]
I did it yesterday when updating production server. Should be good.
