### ISSUE TITLE
A7 - Connexion to Geonode

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#691]
The connexion to Geonode should use specific credentials to allow access to non public data.

**Comment by stufraser1** [comment]
How is progress on this issue? We need to this to operate for v2.0, as we have data that should be used in thinkhazard, but cannot be accessible for public viewing on geonode.

**Comment by stufraser1** [comment]
http://int.geonode-gfdrrlab.org/search/?title__icontains=adm2_fu_raster_v2
http://int.geonode-gfdrrlab.org/search/?title__icontains=adm2_uu_raster_v2

Should remain private in Geonode, but used in ThinkHazard

**Comment by Vampouille** [comment]
Should be fixed by : https://github.com/camptocamp/labs_geonode/pull/2

**Comment by Vampouille** [comment]
With previous PR, following url will allow login with api keys :

* /api/base
* /api/featured
* /api/layers
* /api/maps
* /api/documents

Api URL **not** affected by API Keys :

* /api/keywords
* /api/thesaurus/keywords
* /api/regions
* /api/categories
* /api/groups
* /api/profiles
* /api/owners

Is it match Thinkhazard requirements ?

**Comment by fvanderbiest** [comment]
> Does it matches Thinkhazard requirements ?

TH harvests the GeoNode **API**:
 * **regions**, fields `id`, `name_en`, `level`
 * **documents**, fields `id`, `title`, `regions`, `hazard_type`, `supplemental_information`
 * **layers**, fields `id`, `title`, `regions`, `hazard_set`, `hazard_type`, `supplemental_information`, `hazard_period`, `hazard_unit`, `srid`, `data_update_date`, `metadata_update_date`, `calculation_method_quality`, `scientific_quality`, `download_url`, `detail_url`, `owner__organization`, `typename`

I'm not sure having private regions is relevant here, so this should be good to go.

**Comment by fvanderbiest** [comment]
> Should be fixed by : camptocamp/labs_geonode#2

Is it relevant to contribute upstream ?

**Comment by fvanderbiest** [comment]
This requires #768

**Comment by Vampouille** [comment]
Fixed on TH side by : https://github.com/GFDRR/thinkhazard/pull/769

**Comment by Vampouille** [comment]
> Is it relevant to contribute upstream ?

yes

**Comment by fjacon** [comment]
I think we can close the issue unless I am missing something here.

**Comment by fjacon** [comment]
@fvanderbiest ? can we close ?
