### ISSUE TITLE
A9 - API

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#692]
The API should enable other applications to request the following information:
- [x] Hazard levels for a given hazard type and admin boundaries
- [x] Hazard description for a given hazard type, and levels
- [x] Recommendations for a given hazard, and admin boundaries
- [x] Further resources for a given hazard, and admin boundaries
- [x] Potential combinations of those
- [ ] Logging and tracking of the API use should be integrated in the API design to be able to create analytics on its use.

Following actions need to be done as well:
- [x] Documentation

**Comment by pgiraud** [comment]
@stufraser1 I merged the work on API I initiated several weeks ago.

The documentation for the API is available here:
https://github.com/GFDRR/thinkhazard/blob/master/API.md

A deployed demo is available at http://int.thinkhazard.org

**Comment by stufraser1** [comment]
@fvanderbiest Please complete the outstanding tracking of API use so we can close off the API issue?
Is there any further work planned on API documentation?

**Comment by fjacon** [comment]
@stufraser1 we agreed that logging can be done under support part of contract (see https://docs.google.com/document/d/1CkcyTsuRph-3YfUk9Ye_YNegbLOsK28U002FQHxZGcc/edit# )
I think we should create another issue and maybe not keep it for milestones V2.

**Comment by stufraser1** [comment]
OK, whatever works best for you. Closing
