### ISSUE TITLE
remove whitespace

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#697]
With the addition of the contacts box, the further resource box is pushed further down the page.
To make sure it is as high as possible, can we minimize (without compromising the clean look) the space above the 'Contacts' and 'Further Resources' titles in their respective boxes? Also, can we minimize whitespace around the legend and data source?

**Comment by pgiraud** [comment]
See #694

**Comment by pgiraud** [comment]
Fixed via #694
