### ISSUE TITLE
climate recommendation and contacts not available for 63 GAUL Admin0 units

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#699]
Climate recommendations and contacts are not available for 63 GAUL Admin0 units, which are not listed as a corresponding World Bank country. This is because either they are not recognised as a member state (e.g., Western Sahara), or because they are part of a member state's territory (e.g., Montserrat, Netherlands Antilles)

GFDRR should find a solution to provide climate change recommendations / contacts for those countries.
For Climate Change: Include these GAUL units in location listing, and assign statements according to the region in which they are located.
For Contacts: Include these GAUL units in location listing, and search for / assign contacts as required (though these will fall under non-priority countries)

**Comment by stufraser1** [comment]
@pgiraud 
What would be the best way to supply a revised set of cliamte change statements, for bulk upload? (To address this issue)
In the same format as previously supplied and uploaded, or in the format of the contact listing?

i.e. 1) each hazard in a new column with each country on one row, or 
2) each hazard in a new row against the country repeated in multiple rows

**Comment by pgiraud** [comment]
@stufraser1 sorry for the long delay on this one. Since there is not too much new recommendations relationships with divisions to create and not too much contacts to add, I would probably advice to create those in the admin interface when we're ready.

**Comment by stufraser1** [comment]
Noted. I will manually assign in admin UI, climate statements to those units missing statements, based on geographical proximity to locations with climate statements
