### ISSUE TITLE
Missing date on pdf report

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#705]
THe pdf report states 'The data was published for the last time on .' and appears to be missing the date. This sentence appears at the bottom of the 'About' information, after the reference to GitHub.

**Comment by pgiraud** [comment]
@stufraser1 should this be fixed on the current version deployed in production?

**Comment by stufraser1** [comment]
Ideally yes please

**Comment by pgiraud** [comment]
The fixed code is deployed on the production server.
