### ISSUE TITLE
Clicked icons have unintended white lines

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#733]
Please solve the issue with the placement of some icons in the top bar, where there is a slight white sliver around the icon edge, between the solid colour of the icon, and the coloured circle that appears when an icon is clicked. 

Occurs on LS, TS, VA (the other icons don’t have any circles around them when they are clicked), e.g., 
http://int.thinkhazard.org/en/report/116-indonesia/LS
http://int.thinkhazard.org/en/report/116-indonesia/VA
http://int.thinkhazard.org/en/report/116-indonesia/TS

![image](https://cloud.githubusercontent.com/assets/12515042/23307095/2945b5dc-fa9e-11e6-8cb1-549e6be551b1.png)

**Comment by pgiraud** [comment]
Here's a demo in which I intentionally added a padding around the icon.
http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/th_icons/en/report/116-indonesia/LS

This has in my opinion a better look.

**Comment by pgiraud** [comment]
![screenshot from 2017-03-01 14 22 42](https://cloud.githubusercontent.com/assets/319774/23461512/8b0b48a0-fe8a-11e6-8d17-08a1ca6e889e.png)

**Comment by stufraser1** [comment]
These look good, thank you
