### ISSUE TITLE
distribution_url deprecated in geonode 2.5 and above

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#746]
While harvesting the new geonode version (hosted on http://www.geonode-gfdrrlab.org) from our TH dev server, we noticed an issue related to the `distribution_url` field.

We're currently storing it as a `HazardSet` field during the harvesting step
https://github.com/GFDRR/thinkhazard/blob/master/thinkhazard/models.py#L542-L543

The issue lies in the fact that this field was removed in newer geonode versions, with https://github.com/GeoNode/geonode/issues/2422

@ingenieroariel suggested in his [comment](https://github.com/GeoNode/geonode/issues/2422#issuecomment-183041212) that it was redundant with `Links` as per https://github.com/GeoNode/geonode/blob/2.6.x/geonode/base/models.py#L892-L917 but I'm not sure this is relevant in our case.

Let's take http://45.55.174.20/api/layers/149/ from former lab's geonode as an example, for which `distribution_url` field was set to "http://45.55.174.20/layers/hazard%3Avolc_globalproximalhazard_wgs84".

In the newer geonode version, http://www.geonode-gfdrrlab.org/api/layers/149/ has a `detail_url` field set to "/layers/hazard%3Avolc_globalproximalhazard_wgs84", which could be used as a replacement IMO.

Do you think it's safe to replace the use of `distribution_url` with `detail_url` in TH, in order to match newer geonode versions ?

**Comment by stufraser1** [comment]
I think its safe. We can look to replicate distribution_url in detail_url when we run the new list view, and create a bulk metadata update.
Will assign to ErikKBethke once he is added today to this repo

**Comment by fvanderbiest** [comment]
So, do we agree on the fact that `detail_url` will be a full URL, including server FQDN, as for the previous `distribution_url` field ?

**Comment by fvanderbiest** [comment]
Please note that our change will break the API, eg report for a division for a hazard type:

**GET** `/report/{division_code}/{hazard_type}.json` will now output

``` json
{
  "sources": [
    {
      "detail_url": "http://45.55.174.20/layers/hazard%3Ainunmask_world_stream_6tthres_2_t_50",
      "id": "FL-GLOBAL-GLOFRIS",
      "owner_organization": "GLOFRIS"
    },
  ...
}
```
rather than 
``` json
{
  "sources": [
    {
      "distribution_url": "http://45.55.174.20/layers/hazard%3Ainunmask_world_stream_6tthres_2_t_50",
      "id": "FL-GLOBAL-GLOFRIS",
      "owner_organization": "GLOFRIS"
    },
  ...
}
```

Are there applications relying on this API ?

**Comment by stufraser1** [comment]
@fvanderbiest None that I know of use the API yet.

**Comment by fvanderbiest** [comment]
Great, merging #752 then. Thanks !

**Comment by fvanderbiest** [comment]
Will also require a bulk update of `detail_url` in the geonode db, to have an absolute URL.

**Comment by fvanderbiest** [comment]
> Will also require a bulk update of detail_url in the geonode db, to have an absolute URL.

@Vampouille would actually favor updating TH, and I agree.

**Comment by fvanderbiest** [comment]
Harvesting http://www.geonode-gfdrrlab.org/api/ works fine now.
