### ISSUE TITLE
Add extreme heat recommendations / climate statements

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#750]
@fjacon @fvanderbiest  Can I upload the recommendations / climate change statements now? To the int server? We need to have these live as soon as possible to be pushed to transifex for translation.

**Comment by fjacon** [comment]
@stufraser1 can we wait next week for this ?

**Comment by stufraser1** [comment]
Yes

**Comment by stufraser1** [comment]
@fvanderbiest Please could you advise when this week, this will be ready so I can upload the new statements? Thanks

**Comment by fjacon** [comment]
@stufraser1 let's discuss this tomorrow. I am preparing beforehand a document explaining how we can proceed. I will share it this afternoon.

**Comment by stufraser1** [comment]
Uploading begun, with errors #757
