### ISSUE TITLE
Error uploading technical recomms (new hazards)

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#757]
On int.thinkhazard.org I am unable to save new recommendations to UF or EH or WF.

Error given on pressing save:
_'Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.'_

I have been able to upload climate change statements to newly added hazards EH and UF.
I am unable to view hazard category statements, e.g., http://int.thinkhazard.org/admin/hazardcategory/UF/HIG

**Comment by fjacon** [comment]
@tonio will look into this on monday asap.

**Comment by tonio** [comment]
Should be fixed with #759, which is merged & deployed to int.

**Comment by stufraser1** [comment]
I have uploaded statements to UF and EH successfully. Closing
