### ISSUE TITLE
Contacts Listing - data error

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#763]
Each country / hazard combination can have up to three contacts.

It seems that the contact entries effectively separate out contact #1 from the import table, but merges contact #2 and contact # 3.
E.g., http://int.thinkhazard.org/admin/contact/160
refers to Belgium EQ, which has three contacts with email information provided,

http://int.thinkhazard.org/admin/contact/40
refers to five countries where contact #2 and contact # 3 are merged

Can these be separated?

**Comment by tonio** [comment]
Should be fixed with #765 . I just made another import on integration.

**Comment by stufraser1** [comment]
This looks better, thank you.
However, having solved that, I can now see there were also other errors in the file provided, which were contributing to duplicated entries. Please could you import the attached, updated file?
[hazardCountryList_Organizations_20170609.zip](https://github.com/GFDRR/thinkhazard/files/1064546/hazardCountryList_Organizations_20170609.zip)

**Comment by tonio** [comment]
Looks like attached file is empty.

**Comment by stufraser1** [comment]
very sorry - reattaching
[hazardCountryList_Organizations_20170609.zip](https://github.com/GFDRR/thinkhazard/files/1074282/hazardCountryList_Organizations_20170609.zip)

**Comment by tonio** [comment]
New contacts imported on integration.
