### ISSUE TITLE
Add support for geonode harvesting with api_key 

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#768]
See https://github.com/camptocamp/labs_geonode/pull/2

**Comment by fjacon** [comment]
this PR has been merged
https://github.com/camptocamp/labs_geonode/pull/2
So should we close this @fvanderbiest ?

**Comment by fvanderbiest** [comment]
Done with https://github.com/GFDRR/thinkhazard/pull/769
