### ISSUE TITLE
broken link in french about page

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#776]
Pour en savoir plus, veuillez consulter la [clause de non-responsabilité](http://thinkhazard.org/fr/disclaimer).

**Comment by stufraser1** [comment]
Both links seem to work for me

**Comment by pgiraud** [comment]
Here's what I see:

![screenshot from 2017-07-26 08-55-52](https://user-images.githubusercontent.com/319774/28608425-9ff07f82-71e0-11e7-86b2-6a80e708c6b8.png)

**Comment by stufraser1** [comment]
Cleared my cache, viewed in normal and in private window on Firefox, still not replicated.

**Comment by stufraser1** [comment]
Sorry, I see what you mean now - fixing.

**Comment by stufraser1** [comment]
Fixed in transifex (there was an extra space between the link name and link URL. Will update on next pull of transifex to website. This, to be done when French team have finished their review this month.
