### ISSUE TITLE
Provide form to request for download for private data and/or alternative link to the best open data one

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/thinkhazard#779]
![image](https://user-images.githubusercontent.com/1036189/28468430-f33d333a-6e00-11e7-9d87-6f7129201a33.png)

Now it links to a GeoNode identification page.

**Comment by stufraser1** [comment]
When non-public data is used for hazard classification in TH! (i.e. when view and download are set to 'private'/specific registered users in GeoNode, no legend / data owner is shown, and clicking on 'more details' button takes a user to GeoNode homepage, not a page for the specific data set.

In this use case, we need to provide a message to the user saying something like:
'The data set used to classify this hazard is not publicly available. For information on the dataset and to request access, please complete the form at this link. An alternative openly available dataset is available at ... ' 
[Need to set up a new google form]

**Comment by stufraser1** [comment]
Have added a new category of feedback onto existing google form. Message to direct user to this in correct use cases required - see #778 
Suggestion for best alternative can be made on ad-hoc basis, difficult to do in uniform manner in UI
