### ISSUE TITLE
Hazard data - landslide

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#781]
@fvanderbiest @tonio 

Landslide hazard page still not showing on the public site.
This was removed in June because new data set (LS-GLOBAL-NASA) was incorrectly classified.
LS-GLOBAL-NASA has been disabled (set to not published on GeoNode), please restore landslide page urgently to the public website.

It should now use hazard data as on v1 two global sources: CIESIN / UNISDR

**Comment by tonio** [comment]
Processing currently fails on the server. Our infrastructure is fixing memory issues, and I'll restart processing as soon as fixed.

**Comment by tonio** [comment]
Processing is done on production. I enabled lanslide in the admin preview. Can you please take a look and confirm it's ok before publishing it? Thanks.

**Comment by stufraser1** [comment]
It seems that the LS-GLOBAL-NASA layer is still active in thinkhazard. Is there a chance it needs to be deleted from thinkhazard dB before a reharvest so it disappears? Alternative is that we set data quality to 1 + 1 to make it not appear for now

**Comment by fjacon** [comment]
@stufraser1 can you update LS-GLOBAL-NASA metadata so this dataset will not be prefered to CIESIN / UNISDR ?

**Comment by stufraser1** [comment]
updated Data Quality, reprocessed, publishing now

**Comment by fvanderbiest** [comment]
> Is there a chance it needs to be deleted from thinkhazard dB before a reharvest so it disappears?

I deleted it from the admin db, for the record:
```
thinkhazard_admin#delete from processing.layer where hazardset_id = 'LS-GLOBAL-NASA';
DELETE 1

thinkhazard_admin# delete from processing.output where hazardset_id = 'LS-GLOBAL-NASA';
DELETE 38155

thinkhazard_admin# delete from processing.hazardset where id = 'LS-GLOBAL-NASA';
DELETE 1
```

**Comment by stufraser1** [comment]
Confirmed LS-GLOBAL-NASA no longer present. I will not work offline on a better method to represent the very small areas of high hazard that unduly influence the classified hazard of large areas.
