### ISSUE TITLE
Improved display of further information links

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#782]
Request to have the top 5 links shown, and a drop-down button to expand the box and display additional links - this will keep the page shorter.

**Comment by fjacon** [comment]
@stufraser1 do you want us to go ahead with this ? we can do it this week.

**Comment by stufraser1** [comment]
Yes please

**Comment by tonio** [comment]
Can be tested on integration.

**Comment by stufraser1** [comment]
Looks great, happy with this
