### ISSUE TITLE
http://www.thinkhazard.org/ in bad shape

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#783]
Service is flapping since last hour...
![capture du 2017-08-01 11-53-11](https://user-images.githubusercontent.com/265319/28819922-09f23d16-76b0-11e7-8005-849f87396139.png)

**Comment by stufraser1** [comment]
I am currently reprocessing and it seems some of the v large global flood data are still on there (we couldnt delete in Geonode UI) so Im going to delete those now and reprocess without them.

**Comment by stufraser1** [comment]
I am unable to connect to the geonode server to delete (and still unable to delete them in the geonode UI)
Connecting with sftp@geonode-gfdrrlabs, port 2223, IP 2.25.101.173 and key files that have worked previously.
Please help me to connect, and/or can you delete the following four files:
adm2_fu_raster_v2
adm2_fu_raster_v3
adm2_uu_raster_v2
adm2_uu_raster_v5

**Comment by fvanderbiest** [comment]
I cannot delete `hazard:global_reclassify` as told by Frederic.
Trying to understand what happens here.

**Comment by fvanderbiest** [comment]
> Connecting with sftp@geonode-gfdrrlabs, port 2223, IP 2.25.101.173 and key files that have worked previously.

I restarted the ssh container and I checked your key was imported from github (https://github.com/stufraser1.keys). Can you check again ?

If it still does not work, this probably means the IP changed and/or firewall rules were updated for some reason. Please let us know.

**Comment by stufraser1** [comment]
Connection still times out, unable to connect. Previously my IP changed and camptocamp set the permission to accept a range of IP addresses.

**Comment by fvanderbiest** [comment]
@saimonn can you take a look at this connection issue (server IP is 54.229.171.111) ? Seems out of my scope. Thanks.

**Comment by stufraser1** [comment]
I can access the server now, thank you. Not closing in case original issue is still a problem ('service flapping')
