### ISSUE TITLE
Data map wrong for three hazards

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#785]
The data map shows national level data globally, for the following hazards:
Volcanic (global data only)
Water scarcity (global data only)
Air pollution (no data included in shp)

I've checked the geojson file and display of the map direct from the geojson - there are no problems.

I think the problem is a mismarch in the app.hazardTypes being used by thinkhazard and those used in the geojson. See https://github.com/GFDRR/thinkhazard/blob/master/thinkhazard/static/js/data_map.js#L27-L37

Is it correct that app.hazardtypes in the above code refers to drought as DG and volcanic as VA ?
If so, I will update the geojson and reissue.
I will also add Columns for AIr Pollution (AP) as this does nto exist in the geojson file so is not being found by the interactive map (so shows as national coverage).

Please ensure that the code results in showing 'no data' on the map, an ADM unit has NULL values in geojson at all levels (_GLO, _REG, _NAT, and _SUB)

Thank you

**Comment by stufraser1** [comment]
New geojson, including update hazard types codes (VA and DG, rather than VO and DR) and new columns that should show for Air Pollution as No Data in every country
[Uploading World_Data_Holdings_v5.zip…]()

**Comment by tonio** [comment]
@stufraser1 file upload failed. Could be you please reattach the file?

**Comment by stufraser1** [comment]
[World_Data_Holdings_v5.zip](https://github.com/GFDRR/thinkhazard/files/1196514/World_Data_Holdings_v5.zip)

**Comment by tonio** [comment]
Updated on production.
