### ISSUE TITLE
How is raster cell read to produce ADM2 hazard level

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#789]
Hi 
I have a question which will influence how I process new global tsunami data. We have a series of point values at the coast, rasterized, and ideally want to leave the processing for TH! backend. In some ADM2 units, the raster cells are not contained entirely within the polygon so I'd like to know whether we need to preprocess that layer, or relocate the raster values to the ADM2 centroid to make sure they are accounted for.

In https://github.com/GFDRR/thinkhazard/blob/master/thinkhazard/processing/processing.py exactly how are raster cell values read for each polygon, when analysing non-preprocessed layers? Is a raster cell only assigned to a polygon if it: 1) entirely contained within a polygon, or 2) if any part of the cell intersects with a polygon, or 3) another?

**Comment by fjacon** [comment]
We rasterize the adm2 polygon to use it as a mask on the hazardset raster, and we take in account all touching pixels.
https://github.com/GFDRR/thinkhazard/blob/e050ce23fa31b065bac029de12155ffbae8c55ac/thinkhazard/processing/processing.py#L278
This is option 2 in your question, if any part of the cell intersects with a polygon.
