### ISSUE TITLE
Changing layer Title in Geonode

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#790]
Will changing the layer title in Geonode have negative upstream effects in TH code?
I.e., changing EQ-BANG-KIT-475 to Earthquake Bangladesh KIT-475

Thank you

**Comment by fvanderbiest** [comment]
Not to my knowledge.

**Comment by arnaud-morvan** [comment]
In thinkhazard, geonode layers are identified by layer "id" (field "geonode_id" on thinkhazard side, which is the primary key).
https://github.com/GFDRR/thinkhazard/blob/master/thinkhazard/processing/harvesting.py#L529

The layer name should be used only for display in thinkhazard.
