### ISSUE TITLE
download PDF not working

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#791]
the download PDF is timing out after running for several minutes.
No error message, except from FireFox
![image](https://user-images.githubusercontent.com/12515042/29722429-9f084c5e-89b8-11e7-96b0-e1aaeb88d561.png)

pages tested:
http://thinkhazard.org/en/report/226-somalia
http://thinkhazard.org/en/report/175-nepal

**Comment by fjacon** [comment]
We will look into this in priority today.

**Comment by stufraser1** [comment]
Hi @tonio - any idea if this will be fixed today? Many thanks!

**Comment by fjacon** [comment]
It is working on the dev server : http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/v2/
Should be OK today on prod

**Comment by tonio** [comment]
It's now fixed & deployed to production.

**Comment by stufraser1** [comment]
thanks, tested and it works for me, closing
