### ISSUE TITLE
GTM Global Tsunami Hazard layer - adjustment on DB required

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#793]
Hi
I uploaded the layers GTM Global Tsunami Hazard (=hazardset ID) and one layer (100y RP) had an extra space at the end of the hazardset ID, resulting in error message no layer for HIG and no layer for LOW in 'make complete'.
I corrected this now on geonode, so hazardset ID all match exactly, but it still conducts make complete on the old version, and I get the same error message no layer for HIG and no layer for LOW. The correction should enable the LOW layer to be seen; this wasn't changed for the HIG layer, which matches all others and therefore should have been OK in the first place.

Please could you see if this needs updating in the processing DB - perhaps because that was the only field changed, it did not re-harvest the revised layers as I thought it would.

Also, I've had the make process procedure fail twice now this afternoon.

**Comment by fjacon** [comment]
@stufraser1 we'll look into that asap

**Comment by fvanderbiest** [comment]
The API (https://www.geonode-gfdrrlab.org/api/layers/) indeed exports 7 layers with 3 with RP matching those defined in https://github.com/GFDRR/thinkhazard/blob/e8957a3c94dc542049743bb285916eae3574e988/thinkhazard_processing.yaml#L84-L92

All of them share the same hazard_set: "GTM Global Tsunami Hazard"

```
        "download_url": "/uploaded/layers/ts_mih_rp10.tif",
        "hazard_period": "10",
        "hazard_set": "GTM Global Tsunami Hazard",
        "hazard_type": "tsunami",
--
        "download_url": "/uploaded/layers/ts_mih_rp200.tif",
        "hazard_period": "200",
        "hazard_set": "GTM Global Tsunami Hazard",
        "hazard_type": "tsunami",
--
        "download_url": "/uploaded/layers/ts_mih_rp100.tif",
        "hazard_period": "100",
        "hazard_set": "GTM Global Tsunami Hazard",
        "hazard_type": "tsunami",
--
        "download_url": "/uploaded/layers/ts_mih_rp1000.tif",
        "hazard_period": "1000",
        "hazard_set": "GTM Global Tsunami Hazard",
        "hazard_type": "tsunami",
--
        "download_url": "/uploaded/layers/ts_mih_rp2500.tif",
        "hazard_period": "2500",
        "hazard_set": "GTM Global Tsunami Hazard",
        "hazard_type": "tsunami",
--
        "download_url": "/uploaded/layers/ts_mih_rp500.tif",
        "hazard_period": "500",
        "hazard_set": "GTM Global Tsunami Hazard",
        "hazard_type": "tsunami",
--
        "download_url": "/uploaded/layers/ts_mih_rp50.tif",
        "hazard_period": "50",
        "hazard_set": "GTM Global Tsunami Hazard",
        "hazard_type": "tsunami",
```

TH should work fine in such circumstances.
I'm taking a look at the issue now.

**Comment by fvanderbiest** [comment]
OK, I updated the DB, ran the full make story, and this seems to work:
```
INFO     Completing hazardset GTM Global Tsunami Hazard
INFO       Completed

INFO     GTM Global Tsunami Hazard
INFO       Cleaning previous outputs
INFO       Opening raster files
INFO       Iterating over 21072 administrative divisions
INFO       ... processed 10%
INFO       ... processed 20%
INFO       ... processed 30%
INFO       ... processed 40%
INFO       ... processed 50%
INFO       ... processed 60%
INFO       ... processed 70%
INFO       ... processed 80%
INFO       ... processed 90%
INFO       ... processed 100%
INFO       Closing raster files
INFO       Successfully processed GTM Global Tsunami Hazard, 3965 outputs generated in 0:01:38.350500
```

**Comment by fvanderbiest** [comment]
`make process` is still running in a screen, `make decisiontree` to be done...

**Comment by fvanderbiest** [comment]
All done in production:
```
fvanderbiest@ip-10-42-1-45:/var/www/vhosts/wb-thinkhazard/private/thinkhazard$ make process
.build/venv/bin/process -v
INFO     CY-FSM-KIT
INFO       Cleaning previous outputs
INFO       Opening raster files
INFO       Iterating over 0 administrative divisions
INFO       Closing raster files
INFO     CY-PHIL-KIT
INFO       Cleaning previous outputs
INFO       Opening raster files
INFO       Iterating over 0 administrative divisions
INFO       Closing raster files
INFO     CY-VN-KIT
INFO       Cleaning previous outputs
INFO       Opening raster files
INFO       Iterating over 0 administrative divisions
INFO       Closing raster files
INFO     WF-GLOBAL-CSIRO
INFO       Cleaning previous outputs
INFO       Opening raster files
INFO       Iterating over 38167 administrative divisions
INFO       ... processed 10%
INFO       ... processed 20%
INFO       ... processed 30%
INFO       ... processed 40%
INFO       ... processed 50%
INFO       ... processed 60%
INFO       ... processed 70%
INFO       ... processed 80%
INFO       ... processed 90%
INFO       ... processed 100%
INFO       Closing raster files
INFO       Successfully processed WF-GLOBAL-CSIRO, 38167 outputs generated in 0:07:31.491955
fvanderbiest@ip-10-42-1-45:/var/www/vhosts/wb-thinkhazard/private/thinkhazard$ make decisiontree
.build/venv/bin/decision_tree -v
INFO     Purging previous relations
INFO     Calculating level REG
INFO     Upscaling to PRO
INFO     Upscaling to COU
```

**Comment by stufraser1** [comment]
Looks to have uploaded correctly now. Thank you.

**Comment by stufraser1** [comment]
@fvanderbiest 
I just tried harvest, download, and make complete as we have re-uploaded the GTM GLobal Tsunami layers.
Make complete returns the following:
'INFO     Completing hazardset GTM Global Tsunami Hazard
WARNING  Hazardset GTM Global Tsunami Hazard  incomplete: No layer for level LOW
'
There is a valid 2500y return period layer downloaded, so I'm not sure if the earlier problem has reappeard - please can you check this?

**Comment by fjacon** [comment]
@stufraser1 I am afraid we cannot look into this before Monday. I hope it is not a major problem for you.

**Comment by stufraser1** [comment]
I'm publishing data now to get the rest of data/features up to date. We need to get this tsunami data online as soon as possible, and also fix the translation issue ( #794 -- we've entered translated text but I question whether it is required) so that the responsive layout can be shared and publicised.

**Comment by stufraser1** [comment]
@fjacon - any progress on this yesterday / today? Thanks

**Comment by arnaud-morvan** [comment]
Hello, I've just run harvest, download and complete on production server, GTM Global Tsunami Hazard seems complete. I do not know exactly why but the processing output table have been cleaned, so complete processing is running now ...

**Comment by fjacon** [comment]
@arnaud-morvan is processing over ?

**Comment by fjacon** [comment]
We should have Tsunami data in Chile on preview if everything is OK.

**Comment by stufraser1** [comment]
Previous data had extent longitude [0, 360]
New data (now on geonode) should have extent [-180,180]

**Comment by arnaud-morvan** [comment]
I've relaunch process on GTM Global Tsunami Hazard, relaunch decision_tree and now, we get data for tsunamy in Chili.

**Comment by stufraser1** [comment]
Great, it looks good to publish. Looking in the production server admin preview, it also looks like the square brackets issue (#794, @tonio) might be resolved - not sure until it is published though.
@arnaud-morvan Can I (or you) go ahead and make publish?

**Comment by arnaud-morvan** [comment]
Yes, for me it seems good to publish

**Comment by stufraser1** [comment]
Thank you. Published. Closing.
