### ISSUE TITLE
Commits not showing on about page

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#796]
I made two commits on master branch, re logos on about page. The updated page is not visible (with cache cleared).
https://github.com/GFDRR/thinkhazard/commit/e8957a3c94dc542049743bb285916eae3574e988
https://github.com/GFDRR/thinkhazard/commit/3cea4152f326634ed86bd52f943971309fd190ec

Could you advise and merge if required?
@fjacon @fvanderbiest

**Comment by fjacon** [comment]
@tonio can you check this ? thanks.

**Comment by tonio** [comment]
`master` has just been deployed on production

**Comment by stufraser1** [comment]
Thanks
