### ISSUE TITLE
Restricted data source text - display bug and text improvement

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#805]
1. Possible to add the data source to the text?
E.G.: 'The <firm name> data used to classify the hazard in this area is not publicly available to view or download due to licensing restrictions.' Can we use metadata field 'data owner', to add in the firm name?

2. Bug in whether it shows or not: sometimes shows data, other times in same area (zoomed in) shows restricted msg.
E.g. Hazard data displaying ‘cant be shown’, but is known to be open data, e.g. CY
http://thinkhazard.org/en/report/5767-bangladesh-chittagong-bandarban/CY
 
![image](https://user-images.githubusercontent.com/12515042/35580328-a01e7966-05e0-11e8-90c3-9b8b9222f66c.png)

3. Possible to add a field to table at http://thinkhazard.org/admin/hazardsets, which reflects whether the data will be shown in the map viewer hazard data toggle?

**Comment by fjacon** [comment]
@stufraser1 : I suggest to open 3 different issues.
Meanwhile 
N°1 : should be possible 
N°2 : on your example, the data source is visible
N°3 : should be possible
