### ISSUE TITLE
Modal windows not operating properly

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#810]
When I click on modals - ABout, Data Map, FAQs, the correct one does not open.
At first, the disclaimer repeatedly opens, then after clicking several times, data map might open, but then clicking on about/faq the data map keeps opening.
It did this on int and prod.

**Comment by fjacon** [comment]
@tonio can you look into this ?

**Comment by tonio** [comment]
Well, looks like some of your recent commits (https://github.com/GFDRR/thinkhazard/commit/681a956d6bc2b5a31db30bc0bb9b74f8a60cecac, https://github.com/GFDRR/thinkhazard/commit/54630251930a4dab8702f1a7fd7ee0656b682e9e) breaks translations & formatting.

[Here's](https://github.com/GFDRR/thinkhazard/compare/fix_popups) what I had to do in dev to repair *faq* & *about* services and make modal works (in english).
There was:
 - bad formatting (unescaped string, with missing `gettext`)
 - unescaped `;` char
 - extra closing `</div>`

Changing those strings will involve updating translations where the problem still occurs. You might need to re-add fixed strings I had to removed.

**Comment by stufraser1** [comment]
OK, noted, thank you. Sorry about that, I'll be more careful...

**Comment by tonio** [comment]
@stufraser1 You may start with [my branch](https://github.com/GFDRR/thinkhazard/compare/fix_popups) & fix translations in the way you want, so that we can have it in master, push to transifex.

Or do you want me to merge as is, & have untranslated (& some missing) strings in the meantime?
