### ISSUE TITLE
make publish failed - out of memory 

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#813]
Hi @fjacon 
Make publish (with new CY and EQ data failed today, with message:
Backup thinkhazard_admin to /srv/archives/backups/thinkhazard.2017-10-13T20:53:27.671219.backup
pg_dump: Dumping the contents of table "administrativedivision" failed: PQgetResult() failed.
pg_dump: Error message from server: ERROR:  out of memory
DETAIL:  Failed on request of size 134217728.

Please can you resolve with high priority?

**Comment by tonio** [comment]
I just fix memory issue & do the "make publish" to restore production. Will investigate into the cause of this.

**Comment by stufraser1** [comment]
Thank you very much. Leaving open for investigation, please close if you consider it should be.

**Comment by tonio** [comment]
There are memory errors because of never ending printing threads. They are cause by translations error from #810 . I'd be in favour of merging my hotfix and let you fix translations after. Are you OK with that?

**Comment by stufraser1** [comment]
Yes, that's great. thanks and sorry for the unintended errors - having updated FAQs and About previously, I did not anticipate any problems.
