### ISSUE TITLE
Contacts to be included in API

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#817]
Please can we include contact listing in: GET /report/{division_code}/{hazard_type}.json

**Comment by stufraser1** [comment]
@fjacon  is this something that could be included relatively quickly (next couple of weeks?) 
We're updating the internal project portal with new hazards and the team doing that would ideally be able to access contact listing via the same API request. Thank you

**Comment by fjacon** [comment]
@stufraser1 : @tonio will look into this next week.

**Comment by tonio** [comment]
I may miss something but looks like it's the case already ?

http://thinkhazard.org/report/85/UF.json

![screenshot from 2017-10-23 13-47-56](https://user-images.githubusercontent.com/21686/31887481-1b282e3c-b7e8-11e7-97d8-464e5500db3c.png)

**Comment by stufraser1** [comment]
So they are - in which case, please can you update the 
API notes under 'GET /report/{division_code}/{hazard_type}.json' to say contacts are included?
I.e. "Returns the report for a division and a hazard type. Information includes: Data source, Hazard category and description, Recommendations and climate change statement, List of further resources, and Contact Information."
That would be great, thanks.

**Comment by tonio** [comment]
Docs updated.
