### ISSUE TITLE
New landslide data in

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#828]
NASA 2017 landslide data to be included. Requires pre-processing (area weighted as for flood?)

**Comment by stufraser1** [comment]
Mat. Lets discuss this preprocessing. Should the hazard layer proposal not be funded, I'd like to run some tests in GIS against WB ADM polygons, to see what hazard level results from some areas thresholds.

**Comment by MamadioCMCC** [comment]
New layers for LANDSLIDE hazard have been uploaded: **Global Landslide Hazard Map**
https://www.geonode-gfdrrlab.org/layers/hazard:ls_arup

It uses TH ranking as pixel value, i.e. 1 = VLO, 2 = LOW, 3 = MED and 4 = HIG

This should be the reference layer for global landslide hazard from now on, superceeding SEDAC and GAR layers.

It is based on the combination of these layers:
https://www.geonode-gfdrrlab.org/layers/hazard:ls_nasa_rc
https://www.geonode-gfdrrlab.org/layers/hazard:ls_eq_global_arup
https://www.geonode-gfdrrlab.org/layers/hazard:ls_ppmed_global_arup

**Comment by MamadioCMCC** [comment]
New layer processed and shown as intended.
