### ISSUE TITLE
ADM2 Haz level csv export

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#829]
export to csv does not deal well with comma in ADM name -- fix required:
Moldova, Republic of (ADM0)
Stormont, Dundas and Glengarry (ADM2) - in Ontario Canada
al-Ismailia (ADM1) in Egypt

**Comment by tonio** [comment]
Cannot reproduce. I can open it in LibreOffice (default settings, ie: `"` as string delimiter), and works as expected. comma inside double quotes are ignored.
What tool do you use to open it ? can't you configure the string delimiter when opening it?

**Comment by stufraser1** [comment]
I open in latest version of MS Excel using default settings. Default text delimiter = ''.
I'll investigate further

**Comment by stufraser1** [comment]
@tonio  I replicated this issue in MS Excel (on Mac), in Numbers on Mac, and LibreOffice on Mac.

I am emailing you a set of screenshots, that lead me to ask : is the tet delimiter being stripped out of the file during the csv export function? I suspect it might be, which is why we're seeing strings like "Moldova, Republic Of" being split across two columns. Because this only happens with a few string indicated in the initial comment above, it is easy to miss and may cause problems when other people come to download / use the file. Screenshots coming over email.

**Comment by tonio** [comment]
OK, I can reproduce. CSV for one type & for all types are not generated the same way. I was checking the «all types» one. I can see the error for the «one type» one. I'll digg into it.

**Comment by stufraser1** [comment]
Interesting that you can get all types export to work... when I attempt an 'all types' export it often times out (same when I try one type for FL and more occasionally others, too)

**Comment by tonio** [comment]
Fix deployed on integration.

**Comment by stufraser1** [comment]
I think it is only this combination of datasets that has this issue at present.
So: India, Thailand or Cambodia Cyclone (same data sets as Chittagong - 1 restricted, one not)

Others:
Indonesia Landslide - two datasets, both open to view though (so may not provide a good test)
Mexico earthquake - two datasets, both open to view

**Comment by stufraser1** [comment]
Tested on EH, EQ, and LS single hazard csv downloads. Looks to be fixed, thank you
