### ISSUE TITLE
Admin table - new field

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#834]
Please add a field to the table at http://thinkhazard.org/admin/hazardsets.
This field should indicate whether the data will be shown in the map viewer hazard data toggle (or whether restrictions mean it will not be shown).

Sometimes we expect data to be shown, but it shows with 'data unavailable message'. This table will help to validate issue reported #835

**Comment by tonio** [comment]
Deployed on integration.

**Comment by stufraser1** [comment]
Looks great, and flags the correct layers as hidden. Thank you
