### ISSUE TITLE
Bug - restricted data source text 

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#835]
Bug - restricted data source text sometimes shows when the data source should be open. Other times does not show (i.e. shows legend and data info as expected based on licence for dataset)
Sometimes the initial view shows the data information, then zoomed in it shows restricted text.

E.g. Hazard data displaying ‘cant be shown’, but is known to be open data, e.g. CY
http://thinkhazard.org/en/report/5767-bangladesh-chittagong-bandarban/CY

**Comment by fjacon** [comment]
can be seen on this : 
http://thinkhazard.org/en/report/576-bangladesh-chittagong/CY
CY-GLOBAL-GAR should not be restricted but CY-ASIA is.
Now both are restricted on this example.

**Comment by stufraser1** [comment]
@fjacon I don't think this requires more from me at this stage, correct me if you do need something more from me

**Comment by tonio** [comment]
Fix deployed on int http://int.thinkhazard.org/fr/report/576-bangladesh-chittagong/CY

**Comment by stufraser1** [comment]
In this case, the hazard layer CY-ASIA-IF should not be shown to the user. CY-GLOBAL-GAR15 should be. Can you confirm the restricted layer will show the licence restriction text and not the hazard data on screen, when fully integrated? 
When you click on 'More details' button, the layer does not show publicly on Geonode, which is correct - so should also not show in TH.
Thanks

**Comment by tonio** [comment]
> Can you confirm the restricted layer will show the licence restriction text and not the hazard data on screen, when fully integrated?

It should be the case on integration. You may need to empty your cache to see it.

**Comment by stufraser1** [comment]
This is odd - no its the other end of the problem: I've just cleared my cache and I see the licence restriction text for both layers now!
Viewing on latest mac, latest firefox, private browsing window and normal browsing window. In both cases on the first attempt to show CY-GLOBAL-GAR after clearing the cache (I also deleted Thinkhazard cookies), I sometimes see the legend very briefly before it switches to the restricted licence text.

**Comment by tonio** [comment]
I've check with multiples OS/browser, and it seems correct to me on http://int.thinkhazard.org/fr/report/576-bangladesh-chittagong/CY:

 -  `CY-ASIA-IF`:
![screenshot from 2018-03-16 08-42-05](https://user-images.githubusercontent.com/21686/37511545-7e427116-28ff-11e8-9056-57af4868d31d.png)

 - `CY-GLOBAL-GAR15`:
![screenshot from 2018-03-16 08-42-16](https://user-images.githubusercontent.com/21686/37511568-9372a678-28ff-11e8-85de-35f93738470b.png)

There was a bug with the datasource layer that could stay in the map, but I just fixed it.

**Comment by stufraser1** [comment]
Agreed, seems to work now. Only for Chittagong at present, but expect this is for testing purposes.

**Comment by tonio** [comment]
>  Only for Chittagong at present, but expect this is for testing purposes.

Is there another place where I can test the fix?

**Comment by stufraser1** [comment]
I think it is only this combination of datasets that has this issue at present.
So: India, Thailand or Cambodia Cyclone (same data sets as Chittagong - 1 restricted, one not)

Others:
Indonesia Landslide - two datasets, both open to view though (so may not provide a good test)
Mexico earthquake - two datasets, both open to view

**Comment by fjacon** [comment]
@stufraser1 Can we deploy on production ?

**Comment by stufraser1** [comment]
Yes please
