### ISSUE TITLE
Adequate links to event catalogues?

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#836]
Include adequate links to EMDAT and desinventar as source of recent event catalogues

**Comment by fjacon** [comment]
@stufraser1  as "further ressources" ?

**Comment by stufraser1** [comment]
I think either a link in FAQ, or a 'fixed' further resource that appears on each page, at or near the top of the list.

**Comment by stufraser1** [comment]
Added in new FAQ. Closing
