### ISSUE TITLE
Adequate links to real-time event monitoring platforms

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#837]
For users looking for real-time information on hazards - provide a set of links to platforms providing that information.

**Comment by fjacon** [comment]
@stufraser1 : is it just about adding new 'further resources" ?
Or do you want a new rubric ?

**Comment by stufraser1** [comment]
I think either a link in FAQ, or a 'fixed' small set of links in 'further resources' that appears on each page, at or near the top of the list.

**Comment by stufraser1** [comment]
Added in new FAQ. Closing
