### ISSUE TITLE
Info box placement

### ISSUE THREAD

**Issue by MamadioCMCC** [GFDRR/thinkhazard#852]
![immagine](https://user-images.githubusercontent.com/44863827/49239797-a4005600-f3d1-11e8-84ee-3f1502806f08.png)

Whenever I click on the "?" button, both the button and the textbox are shown as overlay on the header.
I'm using a Win10 laptop, the issue happens on any browser.
Suggestion: move the information below the map legend, and show it by default.

**Comment by tonio** [comment]
CSS were wrongly builded. Just rebuild it on prod & it is fixed.

**Comment by MamadioCMCC** [comment]
Thank you
