### ISSUE TITLE
Update URL for method doc

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#855]
Where references are made to TH methodology, update the link to direct people to the online methods:
https://gfdrr.github.io/thinkhazardmethods/#introduction

Warning - though it will not require new translation, this will invalidate translated strings because the URL will change and string in Transifex will not match. This should be updated in Transifex next time strings are pushed there.

**Comment by MamadioCMCC** [comment]
Fixed in the new internal version.
