### ISSUE TITLE
improve linking to documents

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#856]
Is it possible to link to document URLs, rather than PDFs in GeoNode, and dynamically check and remove any links that are broken?

**Comment by stufraser1** [comment]
If the Geonode record includes a document URL (from the web, e.g. original source) - field:  external document / external URL

Example: https://www.geonode-gfdrrlab.org/documents/343/metadata_detail
External Document link is to https://www.emdat.be/index.php

**Comment by stufraser1** [comment]
This is part of a bigger plan to have the resource section reliant not on documents uploaded to Geonode, but from a direct ML-informed web search / scrape of relevant reports.

**Comment by MamadioCMCC** [comment]
Online slate documentation replaced pdf guide.
