### ISSUE TITLE
Rename layers

### ISSUE THREAD

**Issue by MamadioCMCC** [GFDRR/thinkhazard#860]
The following should be renamed in the "Hazard set" line shown under the map.
 
FL-GLOBAL-FATHOM instead of FL-GLOBAL-SSBN
https://www.geonode-gfdrrlab.org/layers/hazard:adm2_fu_v3_4bit

UF-GLOBAL-FATHOM instead of UF-GLOBAL-SSBN
https://www.geonode-gfdrrlab.org/layers/hazard:adm2_uu_v5_4bit

EQ-CR-WB instead of CR-EQ (all return periods)
https://www.geonode-gfdrrlab.org/layers/hazard%3Acr475krigclip

**Comment by stufraser1** [comment]
Note that the layer names are correct in geonode, but have not been reflected in TH when data has been subsequently harvested and processed.
Perhaps the layers need to be removed from the TH server, and re-harvested from scratch?

**Comment by MamadioCMCC** [comment]
Reharvest fix the issue. Closing.
