### ISSUE TITLE
Data source not showing for EQ for Cote d'Ivoire

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/thinkhazard#862]
The data source is not showing here: http://www.thinkhazard.org/en/report/66-cote-divoire/EQ

But it is showing here: http://www.thinkhazard.org/en/report/94-ghana/EQ when I think it should be the same data layer

**Comment by MamadioCMCC** [comment]
Hi VIvien,
the dataset is shown empty as it does not have hazard data in that area, according to the full view:
https://www.geonode-gfdrrlab.org/layers/hazard:wa475
