### ISSUE TITLE
Revise text when source data is not available to include the name of the data source

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/thinkhazard#863]
The current text is: "The data set used to classify the hazard in this area is not publicly available to view or download due to licensing restrictions. Please contact World Bank for further information"

Which doesn't provide any information. We should include the name of the layer, the name of the organization that produced the layer, and any other relevant information that would enable the user to judge the reliability, and to make a request for the data.

**Comment by stufraser1** [comment]
Prefer to leave it as it is, and when TH takes data off the risk data library database, we can provide more information on the licence type, and we can direct users to the RDL page, where they will be able to see metadata and contact the data provider on that basis. At present, the names of the layers are created for TH, and dont necessarily make sense to a user. The name of the orgnisation should already be included (it isn't everytime but that is another more basic issue to be fixed)
