### ISSUE TITLE
NA areas of global layers ranked as "very low", says restricted information

### ISSUE THREAD

**Issue by MamadioCMCC** [GFDRR/thinkhazard#866]
Example on Cyclone global layer.
This layer (https://www.geonode-gfdrrlab.org/layers/hazard:viento_mundo_tr100_int1) has open license and has NoData in most non-tropical regions (e.g. Europe).
The layer information in the TH page writes same message as restricted license layer: "The data set used to classify the hazard in this area is not publicly available to view or download due to licensing restrictions. Please contact UNISDR for further information.", it should instead say "No coverage for the selected hazard". Also in TH ranking it should be "no information" (no color) instead of "very low".

**Comment by stufraser1** [comment]
The same issue occurs for coastal flood - inland areas should be no data.

We had this issue previously and I thought we had resolved it - at that time I recall we had zeroes in places with nodata; zero value got translated to very low hazard. Changing the data source to have 'nodata' raster value where there truly is no data should have resolved it. 

For a successful application of this, @MamadioCMCC  please can you check the values used in the data used for http://thinkhazard.org/en/report/181-niger/VA and compare it to those used for coastal flood too. In this example there is no volcano information in the southern half of the country, so no hazard level appears in the UI. This is correct and should be replicated in other hazards - the change for this takes place at the raw data level (redfine nodata in the geonode layer and reupload)

**Comment by MamadioCMCC** [comment]
I compared volcanic raster (correctly classified) and coastal flood raster (incorectly classified).
Both have "nodata" as value where there is no hazard; the difference is:
- VO have NoData value = 0
- CF have NoData value = -3.40282306074e+038
I will re-export CF rasters setting NoData value = 0 and likely this will solve the issue.

**Comment by MamadioCMCC** [comment]
CY and EQ layers have all been reclassified in order to have bg=nodata.
However, after harvest process not all layers are correctly imported.
![immagine](https://user-images.githubusercontent.com/44863827/69560422-015ec100-0fac-11ea-8801-2c762da15736.png)

 According to thresholds definitions:

```
      CY:
        hazard_type: strong_wind
        return_periods:
          HIG: 50
          MED: 100
          LOW: 1000
      EQ:
        hazard_type: earthquake
        return_periods:
          HIG: [100, 250]
          MED: [475, 500]
          LOW: [1000, 2500]
```
It should process also:
https://www.geonode-gfdrrlab.org/layers/hazard:viento_mundo_tr100_int1
https://www.geonode-gfdrrlab.org/layers/hazard:gar17pga250
https://www.geonode-gfdrrlab.org/layers/hazard:gar17pga475

Layers have been not been changed apart from nodata reclassify. I checked that origin, resolution and size are the same, then I'm not sure what is causing this issue. I just uploaded again those missing layers, although they already look correct.
Could you please run the harverst again and investigate if the issue persists?

**Comment by MamadioCMCC** [comment]
Solved in THv2 update
