### ISSUE TITLE
Report page HTML title should be more explicit

### ISSUE THREAD

**Issue by pgiraud** [GFDRR/thinkhazard#89]
The current title for any page in the application is "Think hazard".
It could be more verbose. For example: "Think hazard - Morocco - Earthquake report"

**Comment by fvanderbiest** [comment]
Or something like this: "Earthquake report for Morocco - Think hazard, Overcome risk" ?

**Comment by nchauvin-brgm** [comment]
Or more simply: "Earthquake in Morocco – Think Hazard"?

**Comment by pgiraud** [comment]
The main interest of a verbose title is to provide more context for history navigation, for example when the user want to go back to a specific page. In my browser (chrome), I can do a long click on the left arrow and I get the list of page I recently visited within the current tab.
I personally prefer when the website name is found first, ie. is immediately written in the title (left side). Then I like to see the more detailed information on the right.
