### ISSUE TITLE
Browser back button doen't always work

### ISSUE THREAD

**Issue by elemoine** [GFDRR/thinkhazard#95]
There is a case when using the browser's back button does not behave as expected. To reproduce the problem:

* Open http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/thinkhazard/wsgi/report?divisioncode=169
* Select Earthquake
* Hit the browser's back button
* -> The "earthquake" page is still displayed, while the "overview" page should be displayed

**Comment by pgiraud** [comment]
Fixed via #96.
